import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

class AppLocalizations {
  static const supportedLocales = [
    Locale('zh', 'TW'),
    Locale('zh', 'CN'),
    Locale('en', 'US'),
    Locale('ja', 'JP'),
  ];

  static const defaultLocale = Locale('zh', 'TW');

  static const Map<String, Map<String, String>> _strings = {
    'zh_TW': {
      'app_name': '錢錢管家',
      'dashboard': '記帳',
      'detail': '明細',
      'invest': '投資',
      'manage': '管理',
      'yes': '是',
      'no': '否',
      'confirm': '確認',
      'cancel': '取消',
      'save': '保存',
      'save_label': '儲存',
      'delete': '刪除',
      'edit': '編輯',
      'add': '新增',
      'search': '搜索',
      'back': '返回',
      'close': '關閉',
      'update': '更新',
      'all': '全部',
      'loading': '加載中...',
      'error': '錯誤',
      'success': '成功',
      'warning': '警告',
      'no_data': '暫無數據',
      'copy': '複製',
      'undo': '復原',
      'no_records': '沒有記錄',
      'edited_label': '已編輯',
      'no_note': '無備註',
      'view_more': '查看更多',
      'filter_category': '分類',
      'clear_filter': '清除',
      'my_accounts': '我的帳戶',
      'net_assets': '淨資產',
      'assets': '資產',
      'liabilities': '負債',
      'accounts': '賬戶',
      'savings_accounts': '儲蓄帳戶',
      'credit_accounts': '信用帳戶',
      'no_accounts': '還沒有帳戶',
      'add_first_account': '點右上角 + 新增第一個帳戶',
      'confirm_delete_title': '確認刪除',
      'account_type': '帳戶類型',
      'please_select_account_type': '請選擇帳戶類型',
      'please_select': '請選擇',
      'dark_mode': '深色模式',
      'dark_mode_subtitle': '切換深色/淺色介面',
      'language': '語言 / Language',
      'monthly_budget': '月預算',
      'budget_updated': '✓ 預算已更新',
      'budget_progress': '預算進度',
      'remaining_budget': '剩餘預算',
      'daily_avg': '日均支出',
      'recommended_daily': '建議日均',
      'include_fixed': '含固定開銷',
      'prev_month': '上月',
      'this_month': '本月',
      'next_month': '下月',
      'current_month_label': '目前月份',
      'current_month_viewing': '查看：{year}年{month}月',
      'annual_overview_title': '{year} 年度總覽',
      'annual_expense': '年度支出',
      'annual_budget': '年度預算',
      'monthly_expense_chart': '各月支出',
      'year_annual': '年度',
      'no_expense_this_month': '本月尚無支出紀錄',
      'transactions': '筆消費',
      'budget_progress_label': '{date} 預算進度',
      'streak_active': '連續記帳 {n} 天',
      'streak_inactive': '今天還沒記帳（{n} 天）',
      'add_expense': '新增支出',
      'edit_expense': '編輯支出',
      'expense_type': '支出',
      'income': '收入',
      'expense_name': '項目名稱',
      'amount': '金額',
      'date': '日期',
      'category': '分類',
      'note': '備註',
      'optional': '選填',
      'other_date': '其他日期',
      'unlinked_account': '不關聯帳戶',
      'no_balance_effect': '不影響餘額',
      'no_accounts_hint': '請先在「管理」頁新增帳戶',
      'dining': '餐飲',
      'education': '教育',
      'entertainment': '娛樂',
      'transport': '交通',
      'shopping': '購物',
      'medical': '醫療',
      'living': '住居',
      'other': '其他',
      'salary': '薪資',
      'bonus': '獎金',
      'invest_income': '投資',
      'refund': '退款',
      'other_income': '其他收入',
      'fixed_expenses': '固定開銷',
      'add_fixed': '新增固定開銷',
      'add_fixed_hint': '點右上角 + 新增固定開銷',
      'monthly': '每月',
      'yearly': '每年',
      'active': '啟用',
      'inactive': '已停用',
      'period_unit': '期',
      'please_fill_name_amount': '請填寫名稱和金額',
      'please_enter_valid_periods': '請輸入有效的期數',
      'edit_fixed': '編輯固定開銷',
      'basic_info': '基本資訊',
      'name_label': '名稱',
      'fixed_name_hint': '例如：房貸、Netflix',
      'monthly_amount': '每月金額',
      'time_settings': '時間設定',
      'start_month': '開始月份',
      'set_periods': '設定期數',
      'total_periods': '總期數',
      'end_month': '結束月份',
      'current_progress': '目前進度',
      'progress_fmt': '第 {current} 期・已繳 {done} 期・剩 {remaining} 期',
      'notes_optional': '備註（選填）',
      'fixed_notes_hint': '例如：土地銀行房貸，利率 1.78%',
      'backup': '備份',
      'restore': '恢復',
      'export': '導出',
      'backup_data': '備份資料',
      'restore_backup': '恢復備份',
      'export_csv': '匯出 CSV',
      'export_excel': '匯出 Excel',
      'backup_export': '備份與匯出',
      'danger_zone': '危險區',
      'clear_all_expenses': '清除所有支出記錄',
      'clear_all_confirm_title': '確定清除？',
      'clear_all_confirm_content': '所有支出記錄將被永久刪除，無法還原。',
      'all_cleared': '所有記錄已清除',
      'no_backup': '尚無備份檔案',
      'select_backup': '選擇備份',
      'delete_backup_title': '刪除備份？',
      'delete_backup_confirm': '刪除後無法復原，確定要刪除此備份嗎？',
      'backup_deleted': '備份已刪除',
      'delete_failed': '刪除失敗，請稍後再試',
      'no_backup_data': '目前沒有備份資料',
      'confirm_restore_title': '確定還原？',
      'confirm_restore_content': '現有所有資料（支出、固定開銷、帳戶、投資）將被備份內容完整取代，此操作無法還原。',
      'restore_label': '還原',
      'select_month': '選擇月份',
      'backup_success': '✓ 備份成功',
      'restore_success': '✓ 恢復成功',
      'export_success': '✓ 導出成功',
      'backup_saved': '✓ 備份已儲存：{filename}',
      'backup_failed_msg': '備份失敗：{error}',
      'csv_exported': '✓ CSV 已匯出：{filename}',
      'excel_exported': '✓ Excel 已匯出：{filename}',
      'export_failed_msg': '匯出失敗：{error}',
      'expense_records': '支出記錄',
      'restore_failed_msg': '還原失敗：{error}',
      'fixed_monthly_total': '每月 NT\$ {amount}',
      'accounts_count': '{n} 個帳戶',
      'holdings_count': '{n} 檔',
      'count_unit': '{n} 個',
      'periods_completed': '已完成全部 {n} 期',
      'periods_remaining_label': '剩 {n} 期',
      'fixed_start_periods': '{date} 起・共 {n} 期',
      'welcome_name': '歡迎，{name}！',
      'delete_confirm_account': '確定要刪除「{name}」嗎？',
      'search_hint': '搜索支出、固定開銷...',
      'no_results': '沒有找到結果',
      'search_prompt': '輸入搜索詞開始',
      'date_range': '日期範圍',
      'select_start_date': '選擇開始日期',
      'select_end_date': '選擇結束日期',
      'select_category': '選擇分類',
      'done': '完成',
      'help_support': '說明與支援',
      'rewatch_tour': '重新觀看新手導覽',
      'rewatch_tour_subtitle': '再次查看錢錢管家的主要功能與使用方式',
      'report_issue': '回報問題與建議',
      'report_issue_subtitle': '問題回報、功能建議或使用感受',
      'confirm_image': '確認附圖內容',
      'confirm_image_content': '請確認截圖中沒有不想提供的個人資訊，例如身分證字號、銀行帳號、信用卡號、密碼或其他敏感資料。',
      'confirm_submit': '確認送出',
      'feedback_sent': '已送出，謝謝你的回饋。我們會持續改善錢錢管家。',
      'feedback_failed': '送出失敗，請稍後再試。你也可以直接來信 hello@qoryva.com。',
      'feedback_intro': '遇到問題、功能建議或使用感受，都可以在這裡告訴我們。若方便，也可以附上截圖協助我們判斷。',
      'feedback_type': '回饋類型',
      'select_feedback_type': '請選擇回饋類型',
      'issue_description': '問題描述',
      'issue_description_hint': '請描述你遇到的狀況、操作步驟，或希望新增的功能。',
      'please_fill_issue': '請填寫問題描述',
      'please_enter_min_10': '請至少輸入 10 個字',
      'contact_email': '聯絡 Email',
      'contact_email_hint': '如果希望我們回覆你，請留下 Email',
      'invalid_email': 'Email 格式不正確',
      'attach_images': '附加圖片（選填，最多 3 張）',
      'submit': '送出',
      'feedback_legal_note': '請不要在回饋內容中填寫身分證字號、銀行帳號、信用卡號、密碼或其他敏感資料。送出後，我們會使用你提供的內容協助排查問題與改善服務。',
      'feedback_cat_usage': '使用問題',
      'feedback_cat_feature': '功能建議',
      'feedback_cat_data': '資料異常',
      'feedback_cat_invest': '投資頁問題',
      'feedback_cat_backup': '備份 / 還原問題',
      'feedback_cat_other': '其他',
      'please_enter_name': '請填寫名稱',
      'please_enter_amount': '請填寫金額',
      'invalid_amount': '金額無效',
      'confirm_delete': '確定要刪除嗎？',
      'confirm_clear_all': '確定要清除所有數據嗎？此操作無法撤銷。',
      'analysis': '支出分析',
      'this_month_short': '本月',
      'two_months': '雙月',
      'half_year': '半年',
      'invest_overview': '投資總覽',
      'total_value': '總現值',
      'total_cost': '總成本',
      'total_profit': '總損益',
      'holding_detail': '持股明細',
      'no_holdings': '還沒有持股',
      'add_first_invest': '點右上角 + 新增第一筆投資',
      'invest_disclaimer': '投資功能僅供個人紀錄與資訊整理使用，不構成投資建議。投資有風險，請自行判斷。',
      'shares': '股數',
      'current_price': '現價',
      'current_value_label': '現值',
      'est_profit': '預估損益',
      'buy_date': '買入日期',
      'buy_reason': '買入理由',
      'sell_strategy': '出場策略',
      'set_fx_rate': '設定匯率',
      'no_current_price': '尚無現價',
      'query_price': '查詢現價',
      'broker': '券商',
      'no_accounts_invest_hint': '尚未建立帳戶，可在「管理」頁新增',
      'fixed_rate_03': '0.3%（固定）',
      'personal_account': '個人帳號',
      'sign_in_gmail': '使用 Gmail 登入',
      'backup_description': '備份資料 · 接收最新功能通知',
      'google_signin': 'Google 登入',
      'signin_optional': '登入為選填，不影響 App 功能',
      'confirm_logout': '確認登出',
      'logout_note': '登出後不影響本機資料。',
      'logout': '登出',
      'receive_updates': '接收最新消息與功能更新',
      'receive_updates_subtitle': '不定期發送新功能介紹，可隨時關閉',
      'restore_legacy_warning': '⚠ 舊版備份已還原。此備份不含帳戶與投資資料，帳戶已清空，請重新建立或手動校正餘額。',
      'restore_success_msg': '✓ 已還原 {expenses} 筆支出、{accounts} 個帳戶、{holdings} 筆持股',
      'year_label': '{year} 年',
      'month_label': '{month}月',
      'onboarding_rewatch_notice': '可隨時在「說明與支援」重新觀看導覽',
      'backup_list_item': '{expenses} 筆支出・{fixed} 項固定開銷',
      'delete_this_backup': '刪除此備份',
      'shares_value': '{n} 股',
      'fee_and_tax_note': '已扣手續費 {fee}%＋交易稅 0.3%',
      'edit_account': '編輯帳戶',
      'add_account': '新建帳戶',
      'account_settings': '帳戶設定',
      'custom_name': '自訂名稱',
      'balance': '餘額',
      'current_balance': '當前餘額',
      'currency': '貨幣',
      'count_in_total': '計入總資產',
      'edit_entry': '編輯記帳',
      'add_income': '新增收入',
      'type_label': '類型',
      'account_label': '帳戶',
      'today': '今天',
      'yesterday': '昨天',
      'day_before_yesterday': '前天',
      'income_category': '收入類別',
      'expense_category': '支出類別',
      'recommended_items': '{category} 推薦項目',
      'income_detail': '收入明細',
      'expense_detail': '支出明細',
      'note_optional': '備註（選填）',
      'update_entry': '更新記帳',
      'save_income': '儲存收入',
      'save_expense': '儲存支出',
      'name_hint': '項目名稱',
      'edit_holding': '編輯持股',
      'add_investment': '新增投資',
      'select_market': '選擇市場',
      'tw_stocks': '🇹🇼  台股',
      'us_stocks': '🇺🇸  美股',
      'code_section_tw': '股票代碼（例：2330、0050）',
      'code_section_us': '股票代碼（例：AAPL、TSLA）',
      'code_input_hint_tw': '輸入代碼或名稱',
      'broker_fee_section_tw': '券商與手續費（台股）',
      'broker_fee_section_us': '券商與手續費（美股）',
      'fee_label_fmt': '手續費 {fee}',
      'fee_rate': '手續費',
      'tx_tax': '交易稅',
      'trade_info': '交易資訊',
      'auto_fill': '自動帶入',
      'purchase_date': '購買日期',
      'linked_account_optional': '關聯帳戶（選填）',
      'unlinked': '不關聯',
      'account_deduct_note': '買入時將從帳戶扣除總成本；刪除持股時將退回金額',
      'invest_notes_optional': '投資筆記（選填）',
      'sell_timing': '賣出時機',
      'buy_reason_hint': '例如：看好 AI 趨勢',
      'sell_timing_hint': '例如：漲 30% 賣出一半',
      'broker_hint_tw': '輸入券商名稱',
      'enter_stock_code': '請輸入股票代碼',
      'enter_valid_shares': '請輸入有效的股數',
      'enter_valid_cost': '請輸入有效的成本',
      'stock_not_found': '找不到「{code}」，請確認代碼是否正確',
      'this_bimonth': '本雙月',
      'this_half_year': '本半年',
      'deleted_item': '已刪除「{name}」',
      'deleted_holding': '已刪除 {code}',
      'copy_suffix': '（副本）',
      'price_fetch_failed': '無法取得股價，請確認網路或稍後再試',
      'price_updated_all': '已更新 {n} 檔現價',
      'price_updated_partial': '已更新 {updated}/{total} 檔現價',
      'streak_record_daily': '每天記帳可維持連續天數',
      'period_spending_prefix': '{period}的總消費為 ',
      'vs_last_period': '，較上期',
      'spending_increased': '增加',
      'spending_decreased': '減少',
      'app_tagline': '輕鬆管理每一分錢',
      'sign_in_google': '使用 Google 登入',
      'continue_as_guest': '以訪客身分繼續',
      'local_data_note': 'Google 登入為選填，所有財務資料均儲存於本機',
      'welcome_user': '歡迎，{name}！',
      'onboard_skip': '跳過',
      'onboard_next': '下一步',
      'tour_skip': '跳過導覽',
      'tour_prev': '上一步',
      'tour_next': '下一步',
      'tour_done': '完成 ✓',
      'tour_s0_title': '歡迎來到錢錢管家 👋',
      'tour_s0_body': '這套 App 幫你輕鬆管理個人財務、追蹤投資，讓你的錢用得更聰明。跟著導覽了解主要功能！',
      'tour_s1_title': '月份切換',
      'tour_s1_body': '點選不同月份，快速切換瀏覽該月的記帳資料。',
      'tour_s2_title': '預算進度',
      'tour_s2_body': '顯示本月支出佔預算的比例、剩餘預算，以及日均建議消費額。可切換「含固定開銷」。',
      'tour_s3_title': '支出分析',
      'tour_s3_body': '甜甜圈圖呈現各類別支出比例，可切換本月 / 雙月 / 半年範圍，並與上期比較。點選分類列可快速篩選明細。',
      'tour_s4_title': '新增支出',
      'tour_s4_body': '這是主要新增按鈕！在記帳頁點它可新增支出，在投資頁點它可新增持股，在管理頁可新增固定開銷。',
      'tour_s4_hint': '👉 點下方金色按鈕，試著新增一筆支出',
      'tour_s5_title': '支出明細',
      'tour_s5_body': '這裡列出所有支出記錄，可依分類篩選，方便查找特定類型的支出。',
      'tour_s6_title': '長按可編輯或刪除',
      'tour_s6_body': '長按任一筆支出，可以編輯、複製或刪除。也可以左滑出現紅色刪除鍵快速刪除。',
      'tour_s6_hint': '👉 長按下方任一筆記錄，試試看選單功能',
      'tour_s7_title': '投資追蹤',
      'tour_s7_body': '管理你的持股組合，同時支援台股與美股，自動換算台幣，即時計算損益。',
      'tour_s8_title': '即時股價刷新',
      'tour_s8_body': '點此按鈕從 Yahoo Finance 取得最新股價，所有持股損益立即更新。',
      'tour_s9_title': '新增持股',
      'tour_s9_body': '在投資頁點 + 按鈕可以新增持股，搜尋台股或美股代碼，自動帶入名稱與現價。',
      'tour_s9_hint': '👉 點下方金色按鈕，試著新增一筆持股',
      'tour_s10_title': '管理頁面',
      'tour_s10_body': '底部「管理」頁包含帳戶管理、預算設定、備份匯出與意見回報等功能。',
      'tour_s11_title': '帳戶管理',
      'tour_s11_body': '管理儲蓄帳戶和信用卡，支援多幣別，自動計算淨資產總覽。',
      'tour_s12_title': '固定開銷',
      'tour_s12_body': '設定每月固定費用（租金、訂閱服務等），可設定分期期數自動追蹤剩餘。',
      'tour_s13_title': '備份與匯出',
      'tour_s13_body': '備份所有資料到本機，或匯出 CSV / Excel 做進一步分析。建議定期備份！',
      'tour_s14_title': '意見回報',
      'tour_s14_body': '遇到問題或有功能建議？點這裡告訴我們，每一則回饋都是改善的動力。',
      'tour_s14_hint': '👉 點這裡試試看開啟意見回報',
      'tour_s15_title': '導覽完成！🎉',
      'tour_s15_body': '你已了解錢錢管家的主要功能，開始記帳吧！若需要重新觀看，隨時可以在這裡開啟。',
      'slide1_title': '歡迎使用\n錢錢管家',
      'slide1_subtitle': '掌握財務，從這裡開始',
      'slide1_intro': '讓我們花一分鐘介紹各項功能',
      'slide2_title': '輕鬆記錄每筆支出',
      'slide2_subtitle': '分類管理，圓餅圖讓你一目了然消費習慣。',
      'slide2_f1_title': '快速新增',
      'slide2_f1_desc': '點中央 + 按鈕，秒速記帳',
      'slide2_f2_title': '連續記帳',
      'slide2_f2_desc': '每天記帳維持連續天數，養成好習慣',
      'slide2_f3_title': '全文搜尋',
      'slide2_f3_desc': '快速查找任何支出記錄',
      'slide3_title': '聰明設定月預算',
      'slide3_subtitle': '設定月預算，即時追蹤剩餘金額，再也不超支。',
      'slide3_f1_title': '預算進度',
      'slide3_f1_desc': '即時顯示已用比例與剩餘預算',
      'slide3_f2_title': '建議日均消費',
      'slide3_f2_desc': '自動計算每天可花多少，理性決策',
      'slide3_f3_title': '含固定開銷',
      'slide3_f3_desc': '預算計算可包含每月固定開銷',
      'slide4_title': '追蹤投資組合',
      'slide4_subtitle': '記錄持股、成本與損益，台股美股通吃。',
      'slide4_f1_title': '即時現價',
      'slide4_f1_desc': '台股、美股現價一鍵刷新',
      'slide4_f2_title': '多幣別換算',
      'slide4_f2_desc': '自動換算 TWD/USD 損益',
      'slide4_f3_title': '買入理由與策略',
      'slide4_f3_desc': '記錄買入原因與出場計畫',
      'slide5_title': '全面管理財務',
      'slide5_subtitle': '固定開銷、帳戶管理、備份匯出，一切盡在掌握。',
      'slide5_f1_title': '固定開銷',
      'slide5_f1_desc': '房租、訂閱服務等每月固定支出一次設定',
      'slide5_f2_title': '帳戶管理',
      'slide5_f2_desc': '多帳戶、多幣別，即時掌握淨資產',
      'slide5_f3_title': '備份與匯出',
      'slide5_f3_desc': '資料備份、CSV/Excel 匯出，安全無虞',
      'slide6_title': '你已準備好了！',
      'slide6_subtitle': '完成以下步驟，開始掌管你的財務。',
      'slide6_check1': '了解記帳功能',
      'slide6_check2': '了解預算管理',
      'slide6_check3': '了解投資追蹤',
      'slide6_check4': '新增第一筆支出',
      'slide6_cta_enter': '直接進入 App',
      'tour0_title': '歡迎來到錢錢管家 👋',
      'tour0_body': '這套 App 幫你輕鬆管理個人財務、追蹤投資，讓你的錢用得更聰明。跟著導覽了解主要功能！',
      'tour1_title': '月份切換',
      'tour1_body': '點選不同月份，快速切換瀏覽該月的記帳資料。',
      'tour2_title': '預算進度',
      'tour2_body': '顯示本月支出佔預算的比例、剩餘預算，以及日均建議消費額。可切換「含固定開銷」。',
      'tour3_title': '支出分析',
      'tour3_body': '甜甜圈圖呈現各類別支出比例，可切換本月 / 雙月 / 半年範圍，並與上期比較。點選分類列可快速篩選明細。',
      'tour4_title': '新增支出',
      'tour4_body': '這是主要新增按鈕！在記帳頁點它可新增支出，在投資頁點它可新增持股，在管理頁可新增固定開銷。',
      'tour4_hint': '👉 點下方金色按鈕，試著新增一筆支出',
      'tour5_title': '支出明細',
      'tour5_body': '這裡列出所有支出記錄，可依分類篩選，方便查找特定類型的支出。',
      'tour6_title': '長按可編輯或刪除',
      'tour6_body': '長按任一筆支出，可以編輯、複製或刪除。也可以左滑出現紅色刪除鍵快速刪除。',
      'tour6_hint': '👉 長按下方任一筆記錄，試試看選單功能',
      'tour7_title': '投資追蹤',
      'tour7_body': '管理你的持股組合，同時支援台股與美股，自動換算台幣，即時計算損益。',
      'tour8_title': '即時股價刷新',
      'tour8_body': '點此按鈕從 Yahoo Finance 取得最新股價，所有持股損益立即更新。',
      'tour9_title': '新增持股',
      'tour9_body': '在投資頁點 + 按鈕可以新增持股，搜尋台股或美股代碼，自動帶入名稱與現價。',
      'tour9_hint': '👉 點下方金色按鈕，試著新增一筆持股',
      'tour10_title': '管理頁面',
      'tour10_body': '底部「管理」頁包含帳戶管理、預算設定、備份匯出與意見回報等功能。',
      'tour11_title': '帳戶管理',
      'tour11_body': '管理儲蓄帳戶和信用卡，支援多幣別，自動計算淨資產總覽。',
      'tour12_title': '固定開銷',
      'tour12_body': '設定每月固定費用（租金、訂閱服務等），可設定分期期數自動追蹤剩餘。',
      'tour13_title': '備份與匯出',
      'tour13_body': '備份所有資料到本機，或匯出 CSV / Excel 做進一步分析。建議定期備份！',
      'tour14_title': '意見回報',
      'tour14_body': '遇到問題或有功能建議？點這裡告訴我們，每一則回饋都是改善的動力。',
      'tour14_hint': '👉 點這裡試試看開啟意見回報',
      'tour15_title': '導覽完成！🎉',
      'tour15_body': '你已了解錢錢管家的主要功能，開始記帳吧！若需要重新觀看，隨時可以在這裡開啟。',
      'validate_title_empty': '請填寫支出名稱',
      'validate_title_long': '名稱不超過50個字符',
      'validate_amount_empty': '請填寫金額',
      'validate_amount_nan': '金額必須是數字',
      'validate_amount_zero': '金額必須大於 0',
      'validate_amount_large': '金額過大',
      'validate_note_long': '備註不超過200個字符',
      'validate_category_empty': '請選擇分類',
      'validate_date_range': '開始日期不能晚於結束日期',
      'validate_budget_empty': '請填寫預算金額',
      'validate_budget_nan': '預算必須是數字',
      'validate_budget_zero': '預算必須大於 0',
      'validate_fixed_name_empty': '請填寫項目名稱',
      'validate_fixed_name_long': '名稱不超過50個字符',
      'validate_search_long': '搜尋詞不超過100個字符',
      'error_permission': '沒有權限執行此操作',
      'error_network': '網絡連接失敗，請檢查網絡',
      'error_database': '數據庫錯誤，請稍後重試',
      'error_generic': '發生錯誤，請稍後重試',
      'error_unknown': '未知錯誤',
    },
    'zh_CN': {
      'app_name': '钱钱管家',
      'dashboard': '记账',
      'detail': '明细',
      'invest': '投资',
      'manage': '管理',
      'yes': '是',
      'no': '否',
      'confirm': '确认',
      'cancel': '取消',
      'save': '保存',
      'save_label': '保存',
      'delete': '删除',
      'edit': '编辑',
      'add': '新增',
      'search': '搜索',
      'back': '返回',
      'close': '关闭',
      'update': '更新',
      'all': '全部',
      'loading': '加载中...',
      'error': '错误',
      'success': '成功',
      'warning': '警告',
      'no_data': '暂无数据',
      'copy': '复制',
      'undo': '撤销',
      'no_records': '没有记录',
      'edited_label': '已编辑',
      'no_note': '无备注',
      'view_more': '查看更多',
      'filter_category': '分类',
      'clear_filter': '清除',
      'my_accounts': '我的账户',
      'net_assets': '净资产',
      'assets': '资产',
      'liabilities': '负债',
      'accounts': '账户',
      'savings_accounts': '储蓄账户',
      'credit_accounts': '信用账户',
      'no_accounts': '还没有账户',
      'add_first_account': '点右上角 + 新增第一个账户',
      'confirm_delete_title': '确认删除',
      'account_type': '账户类型',
      'please_select_account_type': '请选择账户类型',
      'please_select': '请选择',
      'dark_mode': '深色模式',
      'dark_mode_subtitle': '切换深色/浅色界面',
      'language': '语言 / Language',
      'monthly_budget': '月预算',
      'budget_updated': '✓ 预算已更新',
      'budget_progress': '预算进度',
      'remaining_budget': '剩余预算',
      'daily_avg': '日均支出',
      'recommended_daily': '建议日均',
      'include_fixed': '含固定开销',
      'prev_month': '上月',
      'this_month': '本月',
      'next_month': '下月',
      'current_month_label': '当前月份',
      'current_month_viewing': '查看：{year}年{month}月',
      'annual_overview_title': '{year} 年度总览',
      'annual_expense': '年度支出',
      'annual_budget': '年度预算',
      'monthly_expense_chart': '各月支出',
      'year_annual': '年度',
      'no_expense_this_month': '本月暂无支出记录',
      'transactions': '笔消费',
      'budget_progress_label': '{date} 预算进度',
      'streak_active': '连续记账 {n} 天',
      'streak_inactive': '今天还没记账（{n} 天）',
      'add_expense': '新增支出',
      'edit_expense': '编辑支出',
      'expense_type': '支出',
      'income': '收入',
      'expense_name': '项目名称',
      'amount': '金额',
      'date': '日期',
      'category': '分类',
      'note': '备注',
      'optional': '选填',
      'other_date': '其他日期',
      'unlinked_account': '不关联账户',
      'no_balance_effect': '不影响余额',
      'no_accounts_hint': '请先在「管理」页新增账户',
      'dining': '餐饮',
      'education': '教育',
      'entertainment': '娱乐',
      'transport': '交通',
      'shopping': '购物',
      'medical': '医疗',
      'living': '住居',
      'other': '其他',
      'salary': '薪资',
      'bonus': '奖金',
      'invest_income': '投资',
      'refund': '退款',
      'other_income': '其他收入',
      'fixed_expenses': '固定开销',
      'add_fixed': '新增固定开销',
      'add_fixed_hint': '点右上角 + 新增固定开销',
      'monthly': '每月',
      'yearly': '每年',
      'active': '启用',
      'inactive': '已停用',
      'period_unit': '期',
      'please_fill_name_amount': '请填写名称和金额',
      'please_enter_valid_periods': '请输入有效的期数',
      'edit_fixed': '编辑固定开销',
      'basic_info': '基本信息',
      'name_label': '名称',
      'fixed_name_hint': '例如：房贷、Netflix',
      'monthly_amount': '每月金额',
      'time_settings': '时间设定',
      'start_month': '开始月份',
      'set_periods': '设定期数',
      'total_periods': '总期数',
      'end_month': '结束月份',
      'current_progress': '目前进度',
      'progress_fmt': '第 {current} 期・已缴 {done} 期・剩 {remaining} 期',
      'notes_optional': '备注（选填）',
      'fixed_notes_hint': '例如：土地银行房贷，利率 1.78%',
      'backup': '备份',
      'restore': '恢复',
      'export': '导出',
      'backup_data': '备份资料',
      'restore_backup': '恢复备份',
      'export_csv': '导出 CSV',
      'export_excel': '导出 Excel',
      'backup_export': '备份与导出',
      'danger_zone': '危险区',
      'clear_all_expenses': '清除所有支出记录',
      'clear_all_confirm_title': '确定清除？',
      'clear_all_confirm_content': '所有支出记录将被永久删除，无法还原。',
      'all_cleared': '所有记录已清除',
      'no_backup': '尚无备份文件',
      'select_backup': '选择备份',
      'delete_backup_title': '删除备份？',
      'delete_backup_confirm': '删除后无法恢复，确定要删除此备份吗？',
      'backup_deleted': '备份已删除',
      'delete_failed': '删除失败，请稍后重试',
      'no_backup_data': '目前没有备份数据',
      'confirm_restore_title': '确定还原？',
      'confirm_restore_content': '现有所有数据（支出、固定开销、账户、投资）将被备份内容完整取代，此操作无法还原。',
      'restore_label': '还原',
      'select_month': '选择月份',
      'backup_success': '✓ 备份成功',
      'restore_success': '✓ 恢复成功',
      'export_success': '✓ 导出成功',
      'backup_saved': '✓ 备份已保存：{filename}',
      'backup_failed_msg': '备份失败：{error}',
      'csv_exported': '✓ CSV 已导出：{filename}',
      'excel_exported': '✓ Excel 已导出：{filename}',
      'export_failed_msg': '导出失败：{error}',
      'expense_records': '支出记录',
      'restore_failed_msg': '还原失败：{error}',
      'fixed_monthly_total': '每月 NT\$ {amount}',
      'accounts_count': '{n} 个账户',
      'holdings_count': '{n} 只',
      'count_unit': '{n} 个',
      'periods_completed': '已完成全部 {n} 期',
      'periods_remaining_label': '剩 {n} 期',
      'fixed_start_periods': '{date} 起・共 {n} 期',
      'welcome_name': '欢迎，{name}！',
      'delete_confirm_account': '确定要删除「{name}」吗？',
      'search_hint': '搜索支出、固定开销...',
      'no_results': '没有找到结果',
      'search_prompt': '输入搜索词开始',
      'date_range': '日期范围',
      'select_start_date': '选择开始日期',
      'select_end_date': '选择结束日期',
      'select_category': '选择分类',
      'done': '完成',
      'help_support': '说明与支援',
      'rewatch_tour': '重新观看新手导览',
      'rewatch_tour_subtitle': '再次查看钱钱管家的主要功能与使用方式',
      'report_issue': '回报问题与建议',
      'report_issue_subtitle': '问题回报、功能建议或使用感受',
      'confirm_image': '确认附图内容',
      'confirm_image_content': '请确认截图中没有不想提供的个人信息，例如身份证号、银行账号、信用卡号、密码或其他敏感资料。',
      'confirm_submit': '确认送出',
      'feedback_sent': '已送出，谢谢你的回馈。我们会持续改善钱钱管家。',
      'feedback_failed': '送出失败，请稍后再试。你也可以直接来信 hello@qoryva.com。',
      'feedback_intro': '遇到问题、功能建议或使用感受，都可以在这里告诉我们。若方便，也可以附上截图协助我们判断。',
      'feedback_type': '回馈类型',
      'select_feedback_type': '请选择回馈类型',
      'issue_description': '问题描述',
      'issue_description_hint': '请描述你遇到的状况、操作步骤，或希望新增的功能。',
      'please_fill_issue': '请填写问题描述',
      'please_enter_min_10': '请至少输入 10 个字',
      'contact_email': '联系 Email',
      'contact_email_hint': '如果希望我们回复你，请留下 Email',
      'invalid_email': 'Email 格式不正确',
      'attach_images': '附加图片（选填，最多3张）',
      'submit': '送出',
      'feedback_legal_note': '请不要在回馈内容中填写身份证号、银行账号、信用卡号、密码或其他敏感资料。送出后，我们会使用你提供的内容协助排查问题与改善服务。',
      'feedback_cat_usage': '使用问题',
      'feedback_cat_feature': '功能建议',
      'feedback_cat_data': '资料异常',
      'feedback_cat_invest': '投资页问题',
      'feedback_cat_backup': '备份/还原问题',
      'feedback_cat_other': '其他',
      'please_enter_name': '请填写名称',
      'please_enter_amount': '请填写金额',
      'invalid_amount': '金额无效',
      'confirm_delete': '确定要删除吗？',
      'confirm_clear_all': '确定要清除所有数据吗？此操作无法撤销。',
      'analysis': '支出分析',
      'this_month_short': '本月',
      'two_months': '双月',
      'half_year': '半年',
      'invest_overview': '投资总览',
      'total_value': '总现值',
      'total_cost': '总成本',
      'total_profit': '总损益',
      'holding_detail': '持股明细',
      'no_holdings': '还没有持股',
      'add_first_invest': '点右上角 + 新增第一笔投资',
      'invest_disclaimer': '投资功能仅供个人记录与信息整理使用，不构成投资建议。投资有风险，请自行判断。',
      'shares': '股数',
      'current_price': '现价',
      'current_value_label': '现值',
      'est_profit': '预估损益',
      'buy_date': '买入日期',
      'buy_reason': '买入理由',
      'sell_strategy': '出场策略',
      'set_fx_rate': '设定汇率',
      'no_current_price': '尚无现价',
      'query_price': '查询现价',
      'broker': '券商',
      'no_accounts_invest_hint': '尚未建立账户，可在「管理」页新增',
      'fixed_rate_03': '0.3%（固定）',
      'personal_account': '个人账号',
      'sign_in_gmail': '使用 Gmail 登录',
      'backup_description': '备份数据 · 接收最新功能通知',
      'google_signin': 'Google 登录',
      'signin_optional': '登录为选填，不影响 App 功能',
      'confirm_logout': '确认登出',
      'logout_note': '登出后不影响本机数据。',
      'logout': '登出',
      'receive_updates': '接收最新消息与功能更新',
      'receive_updates_subtitle': '不定期发送新功能介绍，可随时关闭',
      'restore_legacy_warning': '⚠ 旧版备份已还原。此备份不含账户与投资数据，账户已清空，请重新建立或手动校正余额。',
      'restore_success_msg': '✓ 已还原 {expenses} 笔支出、{accounts} 个账户、{holdings} 笔持股',
      'year_label': '{year} 年',
      'month_label': '{month}月',
      'onboarding_rewatch_notice': '可随时在「说明与支援」重新观看导览',
      'backup_list_item': '{expenses} 笔支出·{fixed} 项固定开销',
      'delete_this_backup': '删除此备份',
      'shares_value': '{n} 股',
      'fee_and_tax_note': '已扣手续费 {fee}%＋交易税 0.3%',
      'edit_account': '编辑账户',
      'add_account': '新建账户',
      'account_settings': '账户设置',
      'custom_name': '自定义名称',
      'balance': '余额',
      'current_balance': '当前余额',
      'currency': '货币',
      'count_in_total': '计入总资产',
      'edit_entry': '编辑记账',
      'add_income': '新增收入',
      'type_label': '类型',
      'account_label': '账户',
      'today': '今天',
      'yesterday': '昨天',
      'day_before_yesterday': '前天',
      'income_category': '收入类别',
      'expense_category': '支出类别',
      'recommended_items': '{category} 推荐项目',
      'income_detail': '收入明细',
      'expense_detail': '支出明细',
      'note_optional': '备注（选填）',
      'update_entry': '更新记账',
      'save_income': '保存收入',
      'save_expense': '保存支出',
      'name_hint': '项目名称',
      'edit_holding': '编辑持股',
      'add_investment': '新增投资',
      'select_market': '选择市场',
      'tw_stocks': '🇹🇼  台股',
      'us_stocks': '🇺🇸  美股',
      'code_section_tw': '股票代码（例：2330、0050）',
      'code_section_us': '股票代码（例：AAPL、TSLA）',
      'code_input_hint_tw': '输入代码或名称',
      'broker_fee_section_tw': '券商与手续费（台股）',
      'broker_fee_section_us': '券商与手续费（美股）',
      'fee_label_fmt': '手续费 {fee}',
      'fee_rate': '手续费',
      'tx_tax': '交易税',
      'trade_info': '交易信息',
      'auto_fill': '自动带入',
      'purchase_date': '购买日期',
      'linked_account_optional': '关联账户（选填）',
      'unlinked': '不关联',
      'account_deduct_note': '买入时将从账户扣除总成本；删除持股时将退回金额',
      'invest_notes_optional': '投资笔记（选填）',
      'sell_timing': '卖出时机',
      'buy_reason_hint': '例如：看好 AI 趋势',
      'sell_timing_hint': '例如：涨 30% 卖出一半',
      'broker_hint_tw': '输入券商名称',
      'enter_stock_code': '请输入股票代码',
      'enter_valid_shares': '请输入有效的股数',
      'enter_valid_cost': '请输入有效的成本',
      'stock_not_found': '找不到"{code}"，请确认代码是否正确',
      'this_bimonth': '本双月',
      'this_half_year': '本半年',
      'deleted_item': '已删除「{name}」',
      'deleted_holding': '已删除 {code}',
      'copy_suffix': '（副本）',
      'price_fetch_failed': '无法获取股价，请确认网路或稍后再试',
      'price_updated_all': '已更新 {n} 档现价',
      'price_updated_partial': '已更新 {updated}/{total} 档现价',
      'streak_record_daily': '每天记账可维持连续天数',
      'period_spending_prefix': '{period}的总消费为 ',
      'vs_last_period': '，较上期',
      'spending_increased': '增加',
      'spending_decreased': '减少',
      'app_tagline': '轻松管理每一分钱',
      'sign_in_google': '使用 Google 登录',
      'continue_as_guest': '以访客身份继续',
      'local_data_note': 'Google 登录为选填，所有财务数据均储存于本地',
      'welcome_user': '欢迎，{name}！',
      'onboard_skip': '跳过',
      'onboard_next': '下一步',
      'tour_skip': '跳过引导',
      'tour_prev': '上一步',
      'tour_next': '下一步',
      'tour_done': '完成 ✓',
      'tour_s0_title': '欢迎来到钱钱管家 👋',
      'tour_s0_body': '这款 App 帮你轻松管理个人财务、追踪投资，让你的钱用得更聪明。跟着导览了解主要功能！',
      'tour_s1_title': '月份切换',
      'tour_s1_body': '点选不同月份，快速切换浏览该月的记账数据。',
      'tour_s2_title': '预算进度',
      'tour_s2_body': '显示本月支出占预算的比例、剩余预算，以及日均建议消费额。可切换「含固定开销」。',
      'tour_s3_title': '支出分析',
      'tour_s3_body': '甜甜圈图呈现各类别支出比例，可切换本月 / 双月 / 半年范围，并与上期比较。点选分类列可快速筛选明细。',
      'tour_s4_title': '新增支出',
      'tour_s4_body': '这是主要新增按钮！在记账页点它可新增支出，在投资页点它可新增持股，在管理页可新增固定开销。',
      'tour_s4_hint': '👉 点下方金色按钮，试着新增一笔支出',
      'tour_s5_title': '支出明细',
      'tour_s5_body': '这里列出所有支出记录，可依分类筛选，方便查找特定类型的支出。',
      'tour_s6_title': '长按可编辑或删除',
      'tour_s6_body': '长按任一笔支出，可以编辑、复制或删除。也可以左滑出现红色删除键快速删除。',
      'tour_s6_hint': '👉 长按下方任一笔记录，试试看选单功能',
      'tour_s7_title': '投资追踪',
      'tour_s7_body': '管理你的持股组合，同时支持台股与美股，自动换算台币，即时计算损益。',
      'tour_s8_title': '即时股价刷新',
      'tour_s8_body': '点此按钮从 Yahoo Finance 取得最新股价，所有持股损益立即更新。',
      'tour_s9_title': '新增持股',
      'tour_s9_body': '在投资页点 + 按钮可以新增持股，搜寻台股或美股代码，自动带入名称与现价。',
      'tour_s9_hint': '👉 点下方金色按钮，试着新增一笔持股',
      'tour_s10_title': '管理页面',
      'tour_s10_body': '底部「管理」页包含账户管理、预算设定、备份汇出与意见回报等功能。',
      'tour_s11_title': '账户管理',
      'tour_s11_body': '管理储蓄账户和信用卡，支持多币别，自动计算净资产总览。',
      'tour_s12_title': '固定开销',
      'tour_s12_body': '设定每月固定费用（租金、订阅服务等），可设定分期期数自动追踪剩余。',
      'tour_s13_title': '备份与汇出',
      'tour_s13_body': '备份所有资料到本机，或汇出 CSV / Excel 做进一步分析。建议定期备份！',
      'tour_s14_title': '意见回报',
      'tour_s14_body': '遇到问题或有功能建议？点这里告诉我们，每一则回馈都是改善的动力。',
      'tour_s14_hint': '👉 点这里试试看开启意见回报',
      'tour_s15_title': '导览完成！🎉',
      'tour_s15_body': '你已了解钱钱管家的主要功能，开始记账吧！若需要重新观看，随时可以在这里开启。',
      'slide1_title': '欢迎使用\n钱钱管家',
      'slide1_subtitle': '掌握财务，从这里开始',
      'slide1_intro': '让我们花一分钟介绍各项功能',
      'slide2_title': '轻松记录每笔支出',
      'slide2_subtitle': '分类管理，饼图让你一目了然消费习惯。',
      'slide2_f1_title': '快速新增',
      'slide2_f1_desc': '点中央 + 按钮，秒速记账',
      'slide2_f2_title': '连续记账',
      'slide2_f2_desc': '每天记账维持连续天数，养成好习惯',
      'slide2_f3_title': '全文搜索',
      'slide2_f3_desc': '快速查找任何支出记录',
      'slide3_title': '智能设定月预算',
      'slide3_subtitle': '设定月预算，实时追踪剩余金额，再也不超支。',
      'slide3_f1_title': '预算进度',
      'slide3_f1_desc': '实时显示已用比例与剩余预算',
      'slide3_f2_title': '建议日均消费',
      'slide3_f2_desc': '自动计算每天可花多少，理性决策',
      'slide3_f3_title': '含固定开销',
      'slide3_f3_desc': '预算计算可包含每月固定开销',
      'slide4_title': '追踪投资组合',
      'slide4_subtitle': '记录持股、成本与损益，台股美股通吃。',
      'slide4_f1_title': '即时现价',
      'slide4_f1_desc': '台股、美股现价一键刷新',
      'slide4_f2_title': '多币种换算',
      'slide4_f2_desc': '自动换算 TWD/USD 损益',
      'slide4_f3_title': '买入理由与策略',
      'slide4_f3_desc': '记录买入原因与出场计划',
      'slide5_title': '全面管理财务',
      'slide5_subtitle': '固定开销、账户管理、备份导出，一切尽在掌握。',
      'slide5_f1_title': '固定开销',
      'slide5_f1_desc': '房租、订阅服务等每月固定支出一次设定',
      'slide5_f2_title': '账户管理',
      'slide5_f2_desc': '多账户、多币种，实时掌握净资产',
      'slide5_f3_title': '备份与导出',
      'slide5_f3_desc': '数据备份、CSV/Excel 导出，安全无忧',
      'slide6_title': '你已准备好了！',
      'slide6_subtitle': '完成以下步骤，开始掌管你的财务。',
      'slide6_check1': '了解记账功能',
      'slide6_check2': '了解预算管理',
      'slide6_check3': '了解投资追踪',
      'slide6_check4': '新增第一笔支出',
      'slide6_cta_enter': '直接进入 App',
      'tour0_title': '欢迎来到钱钱管家 👋',
      'tour0_body': '这套 App 帮你轻松管理个人财务、追踪投资，让你的钱用得更聪明。跟着导览了解主要功能！',
      'tour1_title': '月份切换',
      'tour1_body': '点选不同月份，快速切换浏览该月的记账数据。',
      'tour2_title': '预算进度',
      'tour2_body': '显示本月支出占预算的比例、剩余预算，以及日均建议消费额。可切换「含固定开销」。',
      'tour3_title': '支出分析',
      'tour3_body': '甜甜圈图呈现各类别支出比例，可切换本月 / 双月 / 半年范围，并与上期比较。点选分类行可快速筛选明细。',
      'tour4_title': '新增支出',
      'tour4_body': '这是主要新增按钮！在记账页点它可新增支出，在投资页点它可新增持股，在管理页可新增固定开销。',
      'tour4_hint': '👉 点下方金色按钮，试着新增一笔支出',
      'tour5_title': '支出明细',
      'tour5_body': '这里列出所有支出记录，可依分类筛选，方便查找特定类型的支出。',
      'tour6_title': '长按可编辑或删除',
      'tour6_body': '长按任一笔支出，可以编辑、复制或删除。也可以左滑出现红色删除键快速删除。',
      'tour6_hint': '👉 长按下方任一笔记录，试试看菜单功能',
      'tour7_title': '投资追踪',
      'tour7_body': '管理你的持股组合，同时支援台股与美股，自动换算台币，即时计算损益。',
      'tour8_title': '即时股价刷新',
      'tour8_body': '点此按钮从 Yahoo Finance 取得最新股价，所有持股损益立即更新。',
      'tour9_title': '新增持股',
      'tour9_body': '在投资页点 + 按钮可以新增持股，搜索台股或美股代码，自动带入名称与现价。',
      'tour9_hint': '👉 点下方金色按钮，试着新增一笔持股',
      'tour10_title': '管理页面',
      'tour10_body': '底部「管理」页包含账户管理、预算设置、备份导出与意见反馈等功能。',
      'tour11_title': '账户管理',
      'tour11_body': '管理储蓄账户和信用卡，支援多币种，自动计算净资产总览。',
      'tour12_title': '固定开销',
      'tour12_body': '设置每月固定费用（租金、订阅服务等），可设定分期期数自动追踪剩余。',
      'tour13_title': '备份与导出',
      'tour13_body': '备份所有数据到本地，或导出 CSV / Excel 做进一步分析。建议定期备份！',
      'tour14_title': '意见反馈',
      'tour14_body': '遇到问题或有功能建议？点这里告诉我们，每一则反馈都是改善的动力。',
      'tour14_hint': '👉 点这里试试看开启意见反馈',
      'tour15_title': '导览完成！🎉',
      'tour15_body': '你已了解钱钱管家的主要功能，开始记账吧！若需要重新观看，随时可以在这里开启。',
      'validate_title_empty': '请填写支出名称',
      'validate_title_long': '名称不超过50个字符',
      'validate_amount_empty': '请填写金额',
      'validate_amount_nan': '金额必须是数字',
      'validate_amount_zero': '金额必须大于 0',
      'validate_amount_large': '金额过大',
      'validate_note_long': '备注不超过200个字符',
      'validate_category_empty': '请选择分类',
      'validate_date_range': '开始日期不能晚于结束日期',
      'validate_budget_empty': '请填写预算金额',
      'validate_budget_nan': '预算必须是数字',
      'validate_budget_zero': '预算必须大于 0',
      'validate_fixed_name_empty': '请填写项目名称',
      'validate_fixed_name_long': '名称不超过50个字符',
      'validate_search_long': '搜索词不超过100个字符',
      'error_permission': '没有权限执行此操作',
      'error_network': '网络连接失败，请检查网络',
      'error_database': '数据库错误，请稍后重试',
      'error_generic': '发生错误，请稍后重试',
      'error_unknown': '未知错误',
    },
    'en_US': {
      'app_name': 'Money Manager',
      'dashboard': 'Budget',
      'detail': 'Details',
      'invest': 'Invest',
      'manage': 'Manage',
      'yes': 'Yes',
      'no': 'No',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'save': 'Save',
      'save_label': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'search': 'Search',
      'back': 'Back',
      'close': 'Close',
      'update': 'Update',
      'all': 'All',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'warning': 'Warning',
      'no_data': 'No data',
      'copy': 'Duplicate',
      'undo': 'Undo',
      'no_records': 'No records',
      'edited_label': 'Edited',
      'no_note': 'No note',
      'view_more': 'View More',
      'filter_category': 'Category',
      'clear_filter': 'Clear',
      'my_accounts': 'My Accounts',
      'net_assets': 'Net Assets',
      'assets': 'Assets',
      'liabilities': 'Liabilities',
      'accounts': 'Accounts',
      'savings_accounts': 'Savings',
      'credit_accounts': 'Credit',
      'no_accounts': 'No accounts yet',
      'add_first_account': 'Tap + to add your first account',
      'confirm_delete_title': 'Confirm Delete',
      'account_type': 'Account Type',
      'please_select_account_type': 'Please select account type',
      'please_select': 'Please select',
      'dark_mode': 'Dark Mode',
      'dark_mode_subtitle': 'Toggle dark/light interface',
      'language': 'Language',
      'monthly_budget': 'Monthly Budget',
      'budget_updated': '✓ Budget Updated',
      'budget_progress': 'Budget Progress',
      'remaining_budget': 'Remaining',
      'daily_avg': 'Daily Avg',
      'recommended_daily': 'Recommended',
      'include_fixed': 'Inc. Fixed',
      'prev_month': 'Last',
      'this_month': 'This Month',
      'next_month': 'Next',
      'current_month_label': 'Current Month',
      'current_month_viewing': 'Viewing: {year}/{month}',
      'annual_overview_title': '{year} Annual Overview',
      'annual_expense': 'Annual Expense',
      'annual_budget': 'Annual Budget',
      'monthly_expense_chart': 'Monthly Expenses',
      'year_annual': 'Annual',
      'no_expense_this_month': 'No expenses this month',
      'transactions': 'transactions',
      'budget_progress_label': '{date} Budget',
      'streak_active': '{n}-day streak',
      'streak_inactive': 'No record today ({n} days)',
      'add_expense': 'Add Expense',
      'edit_expense': 'Edit Expense',
      'expense_type': 'Expense',
      'income': 'Income',
      'expense_name': 'Name',
      'amount': 'Amount',
      'date': 'Date',
      'category': 'Category',
      'note': 'Note',
      'optional': 'Optional',
      'other_date': 'Other date',
      'unlinked_account': 'No Account',
      'no_balance_effect': 'Balance unaffected',
      'no_accounts_hint': 'Add an account in Manage first',
      'dining': 'Dining',
      'education': 'Education',
      'entertainment': 'Entertainment',
      'transport': 'Transport',
      'shopping': 'Shopping',
      'medical': 'Medical',
      'living': 'Housing',
      'other': 'Other',
      'salary': 'Salary',
      'bonus': 'Bonus',
      'invest_income': 'Investment',
      'refund': 'Refund',
      'other_income': 'Other Income',
      'fixed_expenses': 'Fixed Expenses',
      'add_fixed': 'Add Fixed Expense',
      'add_fixed_hint': 'Tap + to add a fixed expense',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'active': 'Active',
      'inactive': 'Inactive',
      'period_unit': 'pds',
      'please_fill_name_amount': 'Please fill in name and amount',
      'please_enter_valid_periods': 'Please enter valid period count',
      'edit_fixed': 'Edit Fixed Expense',
      'basic_info': 'Basic Info',
      'name_label': 'Name',
      'fixed_name_hint': 'e.g. Mortgage, Netflix',
      'monthly_amount': 'Monthly Amount',
      'time_settings': 'Schedule',
      'start_month': 'Start Month',
      'set_periods': 'Set Periods',
      'total_periods': 'Total Periods',
      'end_month': 'End Month',
      'current_progress': 'Progress',
      'progress_fmt': 'Period {current}・Paid {done}・Left {remaining}',
      'notes_optional': 'Notes (optional)',
      'fixed_notes_hint': 'e.g. Land Bank mortgage, rate 1.78%',
      'backup': 'Backup',
      'restore': 'Restore',
      'export': 'Export',
      'backup_data': 'Backup Data',
      'restore_backup': 'Restore Backup',
      'export_csv': 'Export CSV',
      'export_excel': 'Export Excel',
      'backup_export': 'Backup & Export',
      'danger_zone': 'Danger Zone',
      'clear_all_expenses': 'Clear All Expenses',
      'clear_all_confirm_title': 'Confirm Clear?',
      'clear_all_confirm_content': 'All expense records will be permanently deleted. This cannot be undone.',
      'all_cleared': 'All records cleared',
      'no_backup': 'No backup files',
      'select_backup': 'Select Backup',
      'delete_backup_title': 'Delete Backup?',
      'delete_backup_confirm': 'This cannot be undone. Delete this backup?',
      'backup_deleted': 'Backup deleted',
      'delete_failed': 'Delete failed, please try again',
      'no_backup_data': 'No backups available',
      'confirm_restore_title': 'Confirm Restore?',
      'confirm_restore_content': 'All existing data (expenses, fixed items, accounts, investments) will be replaced by the backup. This cannot be undone.',
      'restore_label': 'Restore',
      'select_month': 'Select Month',
      'backup_success': '✓ Backup Successful',
      'restore_success': '✓ Restore Successful',
      'export_success': '✓ Export Successful',
      'backup_saved': '✓ Backup saved: {filename}',
      'backup_failed_msg': 'Backup failed: {error}',
      'csv_exported': '✓ CSV exported: {filename}',
      'excel_exported': '✓ Excel exported: {filename}',
      'export_failed_msg': 'Export failed: {error}',
      'expense_records': 'Expense Records',
      'restore_failed_msg': 'Restore failed: {error}',
      'fixed_monthly_total': 'NT\$ {amount}/mo',
      'accounts_count': '{n} account(s)',
      'holdings_count': '{n} stock(s)',
      'count_unit': '{n}',
      'periods_completed': 'All {n} periods done',
      'periods_remaining_label': '{n} left',
      'fixed_start_periods': 'from {date} · {n} installments',
      'welcome_name': 'Welcome, {name}!',
      'delete_confirm_account': 'Delete "{name}"?',
      'search_hint': 'Search expenses, fixed items...',
      'no_results': 'No results found',
      'search_prompt': 'Enter a search term to begin',
      'date_range': 'Date Range',
      'select_start_date': 'Select Start Date',
      'select_end_date': 'Select End Date',
      'select_category': 'Select Category',
      'done': 'Done',
      'help_support': 'Help & Support',
      'rewatch_tour': 'Rewatch Tutorial',
      'rewatch_tour_subtitle': 'Replay the main features tour',
      'report_issue': 'Report an Issue',
      'report_issue_subtitle': 'Bug reports, feature requests & feedback',
      'confirm_image': 'Confirm Image Content',
      'confirm_image_content': 'Please make sure the screenshot contains no personal info such as ID numbers, bank accounts, credit cards, passwords, or other sensitive data.',
      'confirm_submit': 'Confirm & Submit',
      'feedback_sent': 'Submitted! Thank you for your feedback. We\'ll keep improving the app.',
      'feedback_failed': 'Submission failed. Please try again later or email hello@qoryva.com.',
      'feedback_intro': 'Share any issues, feature ideas, or general feedback here. Screenshots are welcome to help us investigate.',
      'feedback_type': 'Feedback Type',
      'select_feedback_type': 'Select feedback type',
      'issue_description': 'Description',
      'issue_description_hint': 'Describe your issue, steps to reproduce, or the feature you\'d like to see.',
      'please_fill_issue': 'Please describe the issue',
      'please_enter_min_10': 'Please enter at least 10 characters',
      'contact_email': 'Contact Email',
      'contact_email_hint': 'Leave your email if you\'d like us to reply',
      'invalid_email': 'Invalid email format',
      'attach_images': 'Attach Images (optional, up to 3)',
      'submit': 'Submit',
      'feedback_legal_note': 'Do not include ID numbers, bank accounts, credit cards, passwords or other sensitive data in your feedback. Submitted content will be used to help diagnose issues and improve the app.',
      'feedback_cat_usage': 'Usage Issue',
      'feedback_cat_feature': 'Feature Request',
      'feedback_cat_data': 'Data Anomaly',
      'feedback_cat_invest': 'Investment Issue',
      'feedback_cat_backup': 'Backup / Restore Issue',
      'feedback_cat_other': 'Other',
      'please_enter_name': 'Please enter a name',
      'please_enter_amount': 'Please enter an amount',
      'invalid_amount': 'Invalid amount',
      'confirm_delete': 'Are you sure you want to delete?',
      'confirm_clear_all': 'Delete all data? This cannot be undone.',
      'analysis': 'Spending Analysis',
      'this_month_short': 'Month',
      'two_months': '2 Months',
      'half_year': '6 Months',
      'invest_overview': 'Portfolio',
      'total_value': 'Total Value',
      'total_cost': 'Total Cost',
      'total_profit': 'P&L',
      'holding_detail': 'Holdings',
      'no_holdings': 'No holdings yet',
      'add_first_invest': 'Tap + to add your first investment',
      'invest_disclaimer': 'For personal records only. Not investment advice. Invest at your own risk.',
      'shares': 'Shares',
      'current_price': 'Price',
      'current_value_label': 'Value',
      'est_profit': 'Est. P&L',
      'buy_date': 'Buy Date',
      'buy_reason': 'Buy Reason',
      'sell_strategy': 'Exit Strategy',
      'set_fx_rate': 'Set FX Rate',
      'no_current_price': 'No price data',
      'query_price': 'Fetch Price',
      'broker': 'Broker',
      'no_accounts_invest_hint': 'No account yet. Add one in Manage',
      'fixed_rate_03': '0.3% (fixed)',
      'personal_account': 'Account',
      'sign_in_gmail': 'Sign in with Gmail',
      'backup_description': 'Backup data · Get feature updates',
      'google_signin': 'Sign in with Google',
      'signin_optional': 'Sign-in is optional',
      'confirm_logout': 'Confirm Sign Out',
      'logout_note': 'Signing out won\'t affect local data.',
      'logout': 'Sign Out',
      'receive_updates': 'Receive updates & news',
      'receive_updates_subtitle': 'Occasional highlights, unsubscribe anytime',
      'restore_legacy_warning': '⚠ Legacy backup restored. This backup does not include account or investment data. Accounts cleared. Please recreate or adjust balances manually.',
      'restore_success_msg': '✓ Restored: {expenses} expenses, {accounts} accounts, {holdings} holdings',
      'year_label': '{year}',
      'month_label': 'M{month}',
      'onboarding_rewatch_notice': 'You can rewatch the tour anytime in Help & Support',
      'backup_list_item': '{expenses} expenses · {fixed} fixed items',
      'delete_this_backup': 'Delete backup',
      'shares_value': '{n} shares',
      'fee_and_tax_note': 'After fee {fee}% + 0.3% tax',
      'edit_account': 'Edit Account',
      'add_account': 'New Account',
      'account_settings': 'Account Settings',
      'custom_name': 'Custom Name',
      'balance': 'Balance',
      'current_balance': 'Current Balance',
      'currency': 'Currency',
      'count_in_total': 'Include in Net Assets',
      'edit_entry': 'Edit Entry',
      'add_income': 'Add Income',
      'type_label': 'Type',
      'account_label': 'Account',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'day_before_yesterday': '2 Days Ago',
      'income_category': 'Income Category',
      'expense_category': 'Expense Category',
      'recommended_items': 'Suggested: {category}',
      'income_detail': 'Income Details',
      'expense_detail': 'Expense Details',
      'note_optional': 'Note (optional)',
      'update_entry': 'Update Entry',
      'save_income': 'Save Income',
      'save_expense': 'Save Expense',
      'name_hint': 'Item name',
      'edit_holding': 'Edit Holding',
      'add_investment': 'Add Investment',
      'select_market': 'Select Market',
      'tw_stocks': '🇹🇼  Taiwan',
      'us_stocks': '🇺🇸  US Stocks',
      'code_section_tw': 'Symbol (e.g. 2330, 0050)',
      'code_section_us': 'Symbol (e.g. AAPL, TSLA)',
      'code_input_hint_tw': 'Enter code or name',
      'broker_fee_section_tw': 'Broker & Fee (TW)',
      'broker_fee_section_us': 'Broker & Fee (US)',
      'fee_label_fmt': 'Fee {fee}',
      'fee_rate': 'Fee Rate',
      'tx_tax': 'Trans. Tax',
      'trade_info': 'Trade Info',
      'auto_fill': 'Auto-filled',
      'purchase_date': 'Purchase Date',
      'linked_account_optional': 'Link Account (optional)',
      'unlinked': 'None',
      'account_deduct_note': 'Purchase cost deducted from account; refunded on deletion.',
      'invest_notes_optional': 'Investment Notes (optional)',
      'sell_timing': 'Exit Timing',
      'buy_reason_hint': 'e.g. Bullish on AI trend',
      'sell_timing_hint': 'e.g. Sell half at +30%',
      'broker_hint_tw': 'Enter broker name',
      'enter_stock_code': 'Please enter stock symbol',
      'enter_valid_shares': 'Please enter valid shares',
      'enter_valid_cost': 'Please enter valid cost',
      'stock_not_found': 'Symbol "{code}" not found. Please verify the code.',
      'this_bimonth': 'Bi-Monthly',
      'this_half_year': 'Six Months',
      'deleted_item': '"{name}" deleted',
      'deleted_holding': '{code} deleted',
      'copy_suffix': ' (Copy)',
      'price_fetch_failed': 'Failed to fetch price. Check your connection.',
      'price_updated_all': 'Updated {n} prices',
      'price_updated_partial': 'Updated {updated}/{total} prices',
      'streak_record_daily': 'Record daily to maintain your streak',
      'period_spending_prefix': 'Spending for {period}: ',
      'vs_last_period': ', vs. last period',
      'spending_increased': '↑',
      'spending_decreased': '↓',
      'app_tagline': 'Manage every penny, effortlessly',
      'sign_in_google': 'Sign in with Google',
      'continue_as_guest': 'Continue as Guest',
      'local_data_note': 'Google sign-in is optional. All data is stored locally on your device.',
      'welcome_user': 'Welcome, {name}!',
      'onboard_skip': 'Skip',
      'onboard_next': 'Next',
      'tour_skip': 'Skip Tour',
      'tour_prev': 'Back',
      'tour_next': 'Next',
      'tour_done': 'Done ✓',
      'tour_s0_title': 'Welcome to Money Manager 👋',
      'tour_s0_body': 'This app helps you easily manage personal finances and track investments. Follow the guide to discover the main features!',
      'tour_s1_title': 'Month Navigation',
      'tour_s1_body': 'Tap different months to quickly switch between your monthly records.',
      'tour_s2_title': 'Budget Progress',
      'tour_s2_body': 'Shows your spending vs. budget ratio, remaining budget, and recommended daily spend. Toggle "Include Fixed Expenses".',
      'tour_s3_title': 'Spending Analysis',
      'tour_s3_body': 'Donut chart shows spending by category. Switch between monthly/bimonthly/half-year views and compare to last period. Tap a category row to filter details.',
      'tour_s4_title': 'Add Transaction',
      'tour_s4_body': 'This is the main add button! Tap it on the Budget tab to add expenses, on Invest tab to add holdings, on Manage tab to add fixed expenses.',
      'tour_s4_hint': '👉 Tap the gold button below to try adding an expense',
      'tour_s5_title': 'Transaction Details',
      'tour_s5_body': 'Lists all expense records. Filter by category to find specific types of transactions.',
      'tour_s6_title': 'Long-press to Edit or Delete',
      'tour_s6_body': 'Long-press any expense to edit, copy, or delete it. You can also swipe left for a quick delete button.',
      'tour_s6_hint': '👉 Long-press a record below to try the menu',
      'tour_s7_title': 'Investment Tracking',
      'tour_s7_body': 'Manage your portfolio with Taiwan and US stock support. Auto-converts to TWD and calculates gains in real-time.',
      'tour_s8_title': 'Live Price Refresh',
      'tour_s8_body': 'Tap this button to fetch the latest prices from Yahoo Finance. All holdings update instantly.',
      'tour_s9_title': 'Add Holding',
      'tour_s9_body': 'Tap + on the Invest tab to add a holding. Search by stock code to auto-fill name and current price.',
      'tour_s9_hint': '👉 Tap the gold button below to try adding a holding',
      'tour_s10_title': 'Manage',
      'tour_s10_body': 'The Manage tab includes account management, budget settings, backup/export, and feedback.',
      'tour_s11_title': 'Account Management',
      'tour_s11_body': 'Manage savings accounts and credit cards with multi-currency support. Automatically calculates net assets.',
      'tour_s12_title': 'Fixed Expenses',
      'tour_s12_body': 'Set recurring monthly fees (rent, subscriptions, etc.) with installment periods to track remaining payments.',
      'tour_s13_title': 'Backup & Export',
      'tour_s13_body': 'Back up all data locally or export as CSV/Excel for further analysis. Back up regularly!',
      'tour_s14_title': 'Feedback',
      'tour_s14_body': 'Have a problem or suggestion? Tap here to tell us — every piece of feedback drives improvement.',
      'tour_s14_hint': '👉 Tap here to try opening feedback',
      'tour_s15_title': 'Tour Complete! 🎉',
      'tour_s15_body': "You've learned the main features of Money Manager. Start tracking your finances! Tap here anytime to rewatch the tour.",
      'slide1_title': 'Welcome to\nMoney Manager',
      'slide1_subtitle': 'Take control of your finances, starting here',
      'slide1_intro': 'Let us take a minute to walk you through the features',
      'slide2_title': 'Track Every Expense Easily',
      'slide2_subtitle': 'Categorize spending and see patterns with charts.',
      'slide2_f1_title': 'Quick Add',
      'slide2_f1_desc': 'Tap the center + button to log an expense instantly',
      'slide2_f2_title': 'Daily Streak',
      'slide2_f2_desc': 'Keep a daily streak to build good financial habits',
      'slide2_f3_title': 'Full-Text Search',
      'slide2_f3_desc': 'Find any expense record instantly',
      'slide3_title': 'Smart Monthly Budget',
      'slide3_subtitle': 'Set a monthly budget, track spending in real time, never overspend again.',
      'slide3_f1_title': 'Budget Progress',
      'slide3_f1_desc': 'See used percentage and remaining budget instantly',
      'slide3_f2_title': 'Daily Spending Guide',
      'slide3_f2_desc': 'Automatically calculates how much you can spend per day',
      'slide3_f3_title': 'Include Fixed Costs',
      'slide3_f3_desc': 'Budget calculation can include monthly fixed costs',
      'slide4_title': 'Track Your Portfolio',
      'slide4_subtitle': 'Track holdings, cost basis, and P&L for both TW and US stocks.',
      'slide4_f1_title': 'Live Prices',
      'slide4_f1_desc': 'One-tap refresh for TW and US stock prices',
      'slide4_f2_title': 'Multi-Currency',
      'slide4_f2_desc': 'Automatically convert TWD/USD profit & loss',
      'slide4_f3_title': 'Buy Reason & Strategy',
      'slide4_f3_desc': 'Record why you bought and your exit plan',
      'slide5_title': 'Full Financial Control',
      'slide5_subtitle': 'Fixed costs, account management, and backups — all in one place.',
      'slide5_f1_title': 'Fixed Costs',
      'slide5_f1_desc': 'Set up rent, subscriptions, and other fixed monthly expenses',
      'slide5_f2_title': 'Account Management',
      'slide5_f2_desc': 'Multiple accounts and currencies, track net assets in real time',
      'slide5_f3_title': 'Backup & Export',
      'slide5_f3_desc': 'Backup data and export to CSV/Excel, safe and secure',
      'slide6_title': "You're All Set!",
      'slide6_subtitle': 'Complete the steps below to start managing your finances.',
      'slide6_check1': 'Learned about expense tracking',
      'slide6_check2': 'Learned about budget management',
      'slide6_check3': 'Learned about investment tracking',
      'slide6_check4': 'Add your first expense',
      'slide6_cta_enter': 'Enter App',
      'tour0_title': 'Welcome to Money Manager 👋',
      'tour0_body': 'This app helps you manage personal finances and track investments. Follow the tour to learn the main features!',
      'tour1_title': 'Month Navigation',
      'tour1_body': "Tap a month to quickly switch and view that month's expense data.",
      'tour2_title': 'Budget Progress',
      'tour2_body': "Shows this month's spending ratio, remaining budget, and daily suggested spending. Toggle to include fixed costs.",
      'tour3_title': 'Spending Analysis',
      'tour3_body': 'A donut chart shows spending by category. Switch between monthly, bi-monthly, and half-year views. Tap a category row to filter details.',
      'tour4_title': 'Add Expense',
      'tour4_body': 'This is the main add button! Tap it on the budget page to add an expense, on investments to add a stock, and on manage to add a fixed cost.',
      'tour4_hint': '👉 Tap the gold button below to add an expense',
      'tour5_title': 'Expense Details',
      'tour5_body': 'All expense records are listed here. Filter by category to find specific types of spending.',
      'tour6_title': 'Long Press to Edit or Delete',
      'tour6_body': 'Long press any expense to edit, copy, or delete. Swipe left for a quick delete button.',
      'tour6_hint': '👉 Long press any record below to try the context menu',
      'tour7_title': 'Investment Tracking',
      'tour7_body': 'Manage your stock portfolio. Supports TW and US stocks, auto-converts to TWD, and calculates P&L in real time.',
      'tour8_title': 'Live Price Refresh',
      'tour8_body': 'Tap this button to fetch the latest prices from Yahoo Finance and update all holding P&L instantly.',
      'tour9_title': 'Add Holdings',
      'tour9_body': 'Tap + on the investment page to add a stock holding. Search by TW or US ticker and the name and price fill in automatically.',
      'tour9_hint': '👉 Tap the gold button below to add a holding',
      'tour10_title': 'Manage Page',
      'tour10_body': 'The Manage tab includes account management, budget settings, backup/export, and feedback.',
      'tour11_title': 'Account Management',
      'tour11_body': 'Manage savings accounts and credit cards across multiple currencies. Net assets are calculated automatically.',
      'tour12_title': 'Fixed Costs',
      'tour12_body': 'Set up monthly fixed costs (rent, subscriptions, etc.) and track installment progress automatically.',
      'tour13_title': 'Backup & Export',
      'tour13_body': 'Backup all data locally or export to CSV/Excel for further analysis. Regular backups recommended!',
      'tour14_title': 'Feedback',
      'tour14_body': 'Found a bug or have a feature request? Let us know — every piece of feedback helps us improve.',
      'tour14_hint': '👉 Tap here to try opening the feedback form',
      'tour15_title': 'Tour Complete! 🎉',
      'tour15_body': "You've learned the main features of Money Manager — start budgeting! You can always rewatch the tour here.",
      'validate_title_empty': 'Please enter an expense name',
      'validate_title_long': 'Name must be 50 characters or fewer',
      'validate_amount_empty': 'Please enter an amount',
      'validate_amount_nan': 'Amount must be a number',
      'validate_amount_zero': 'Amount must be greater than 0',
      'validate_amount_large': 'Amount is too large',
      'validate_note_long': 'Note must be 200 characters or fewer',
      'validate_category_empty': 'Please select a category',
      'validate_date_range': 'Start date cannot be after end date',
      'validate_budget_empty': 'Please enter a budget amount',
      'validate_budget_nan': 'Budget must be a number',
      'validate_budget_zero': 'Budget must be greater than 0',
      'validate_fixed_name_empty': 'Please enter an item name',
      'validate_fixed_name_long': 'Name must be 50 characters or fewer',
      'validate_search_long': 'Search query must be 100 characters or fewer',
      'error_permission': 'No permission to perform this action',
      'error_network': 'Network connection failed. Please check your connection.',
      'error_database': 'Database error. Please try again later.',
      'error_generic': 'An error occurred. Please try again later.',
      'error_unknown': 'Unknown error',
    },
    'ja_JP': {
      'app_name': 'マネーマネージャー',
      'dashboard': '家計簿',
      'detail': '明細',
      'invest': '投資',
      'manage': '管理',
      'yes': 'はい',
      'no': 'いいえ',
      'confirm': '確認',
      'cancel': 'キャンセル',
      'save': '保存',
      'save_label': '保存',
      'delete': '削除',
      'edit': '編集',
      'add': '追加',
      'search': '検索',
      'back': '戻る',
      'close': '閉じる',
      'update': '更新',
      'all': 'すべて',
      'loading': '読み込み中...',
      'error': 'エラー',
      'success': '成功',
      'warning': '警告',
      'no_data': 'データなし',
      'copy': '複製',
      'undo': '元に戻す',
      'no_records': '記録なし',
      'edited_label': '編集済み',
      'no_note': 'メモなし',
      'view_more': '詳細を見る',
      'filter_category': 'カテゴリー',
      'clear_filter': 'クリア',
      'my_accounts': 'マイアカウント',
      'net_assets': '純資産',
      'assets': '資産',
      'liabilities': '負債',
      'accounts': '口座',
      'savings_accounts': '貯蓄口座',
      'credit_accounts': 'クレジット',
      'no_accounts': '口座がありません',
      'add_first_account': '右上の + をタップして最初の口座を追加',
      'confirm_delete_title': '削除の確認',
      'account_type': '口座タイプ',
      'please_select_account_type': '口座タイプを選択してください',
      'please_select': '選択してください',
      'dark_mode': 'ダークモード',
      'dark_mode_subtitle': 'ダーク/ライト切替',
      'language': '言語 / Language',
      'monthly_budget': '月次予算',
      'budget_updated': '✓ 予算を更新しました',
      'budget_progress': '予算進捗',
      'remaining_budget': '残予算',
      'daily_avg': '日平均支出',
      'recommended_daily': '推奨日額',
      'include_fixed': '固定費含む',
      'prev_month': '先月',
      'this_month': '今月',
      'next_month': '来月',
      'current_month_label': '今月',
      'current_month_viewing': '表示中：{year}年{month}月',
      'annual_overview_title': '{year}年 年間概要',
      'annual_expense': '年間支出',
      'annual_budget': '年間予算',
      'monthly_expense_chart': '月別支出',
      'year_annual': '年間',
      'no_expense_this_month': '今月の支出はありません',
      'transactions': '件',
      'budget_progress_label': '{date} 予算',
      'streak_active': '{n}日連続',
      'streak_inactive': '今日未記録（{n}日）',
      'add_expense': '支出を追加',
      'edit_expense': '支出を編集',
      'expense_type': '支出',
      'income': '収入',
      'expense_name': '項目名',
      'amount': '金額',
      'date': '日付',
      'category': 'カテゴリー',
      'note': 'メモ',
      'optional': '任意',
      'other_date': 'その他の日付',
      'unlinked_account': '口座なし',
      'no_balance_effect': '残高に影響しない',
      'no_accounts_hint': '先に「管理」で口座を追加してください',
      'dining': '飲食',
      'education': '教育',
      'entertainment': '娯楽',
      'transport': '交通',
      'shopping': 'ショッピング',
      'medical': '医療',
      'living': '住居',
      'other': 'その他',
      'salary': '給与',
      'bonus': 'ボーナス',
      'invest_income': '投資',
      'refund': '返金',
      'other_income': 'その他収入',
      'fixed_expenses': '固定費',
      'add_fixed': '固定費を追加',
      'add_fixed_hint': '右上の + をタップして固定費を追加',
      'monthly': '毎月',
      'yearly': '毎年',
      'active': '有効',
      'inactive': '無効',
      'period_unit': '回',
      'please_fill_name_amount': '名前と金額を入力してください',
      'please_enter_valid_periods': '有効な回数を入力してください',
      'edit_fixed': '固定費を編集',
      'basic_info': '基本情報',
      'name_label': '名称',
      'fixed_name_hint': '例：住宅ローン、Netflix',
      'monthly_amount': '月額',
      'time_settings': 'スケジュール',
      'start_month': '開始月',
      'set_periods': '期間を設定',
      'total_periods': '総期数',
      'end_month': '終了月',
      'current_progress': '進行状況',
      'progress_fmt': '第{current}回・支払済{done}回・残{remaining}回',
      'notes_optional': 'メモ（任意）',
      'fixed_notes_hint': '例：土地銀行住宅ローン、金利1.78%',
      'backup': 'バックアップ',
      'restore': '復元',
      'export': 'エクスポート',
      'backup_data': 'データをバックアップ',
      'restore_backup': 'バックアップを復元',
      'export_csv': 'CSVでエクスポート',
      'export_excel': 'Excelレポートを出力',
      'backup_export': 'バックアップ＆エクスポート',
      'danger_zone': '危険ゾーン',
      'clear_all_expenses': 'すべての支出を削除',
      'clear_all_confirm_title': '削除を確認',
      'clear_all_confirm_content': 'すべての支出記録が永久に削除されます。元に戻せません。',
      'all_cleared': 'すべての記録を削除しました',
      'no_backup': 'バックアップファイルなし',
      'select_backup': 'バックアップを選択',
      'delete_backup_title': 'バックアップを削除？',
      'delete_backup_confirm': '元に戻せません。このバックアップを削除しますか？',
      'backup_deleted': 'バックアップを削除しました',
      'delete_failed': '削除失敗。後で再試行してください',
      'no_backup_data': 'バックアップがありません',
      'confirm_restore_title': '復元しますか？',
      'confirm_restore_content': '現在のすべてのデータ（支出・固定費・口座・投資）がバックアップで上書きされます。元に戻せません。',
      'restore_label': '復元',
      'select_month': '月を選択',
      'backup_success': '✓ バックアップ完了',
      'restore_success': '✓ 復元完了',
      'export_success': '✓ エクスポート完了',
      'backup_saved': '✓ バックアップ保存：{filename}',
      'backup_failed_msg': 'バックアップ失敗：{error}',
      'csv_exported': '✓ CSVエクスポート：{filename}',
      'excel_exported': '✓ Excelエクスポート：{filename}',
      'export_failed_msg': 'エクスポート失敗：{error}',
      'expense_records': '支出記録',
      'restore_failed_msg': '復元失敗：{error}',
      'fixed_monthly_total': '毎月 NT\$ {amount}',
      'accounts_count': '{n} 口座',
      'holdings_count': '{n} 銘柄',
      'count_unit': '{n} 件',
      'periods_completed': '全 {n} 回完了',
      'periods_remaining_label': '残り {n} 回',
      'fixed_start_periods': '{date} から・全 {n} 回',
      'welcome_name': 'ようこそ、{name}さん！',
      'delete_confirm_account': '「{name}」を削除しますか？',
      'search_hint': '支出・固定費を検索...',
      'no_results': '結果が見つかりません',
      'search_prompt': '検索ワードを入力してください',
      'date_range': '日付範囲',
      'select_start_date': '開始日を選択',
      'select_end_date': '終了日を選択',
      'select_category': 'カテゴリを選択',
      'done': '完了',
      'help_support': 'ヘルプ＆サポート',
      'rewatch_tour': 'チュートリアルを再視聴',
      'rewatch_tour_subtitle': 'アプリの主な機能を再確認',
      'report_issue': '問題を報告',
      'report_issue_subtitle': 'バグ報告・機能提案・感想',
      'confirm_image': '画像内容を確認',
      'confirm_image_content': 'スクリーンショットに身分証番号・銀行口座・クレジットカード番号・パスワードなどの個人情報が含まれていないことを確認してください。',
      'confirm_submit': '確認して送信',
      'feedback_sent': '送信完了！フィードバックありがとうございます。継続的に改善してまいります。',
      'feedback_failed': '送信失敗しました。後でもう一度お試しいただくか、hello@qoryva.com までご連絡ください。',
      'feedback_intro': '問題・機能提案・使用感想など、お気軽にお知らせください。スクリーンショットがあると調査の参考になります。',
      'feedback_type': 'フィードバック種類',
      'select_feedback_type': 'フィードバック種類を選択',
      'issue_description': '問題の説明',
      'issue_description_hint': '状況・操作手順、または追加してほしい機能を説明してください。',
      'please_fill_issue': '問題を説明してください',
      'please_enter_min_10': '10文字以上入力してください',
      'contact_email': '連絡先メール',
      'contact_email_hint': '返信を希望する場合はメールを残してください',
      'invalid_email': 'メール形式が正しくありません',
      'attach_images': '画像を添付（任意、最大3枚）',
      'submit': '送信',
      'feedback_legal_note': 'フィードバック内容に身分証番号・銀行口座・クレジットカード番号・パスワードなどを含めないでください。提供された内容は問題解決とサービス改善に使用されます。',
      'feedback_cat_usage': '使用上の問題',
      'feedback_cat_feature': '機能提案',
      'feedback_cat_data': 'データ異常',
      'feedback_cat_invest': '投資ページの問題',
      'feedback_cat_backup': 'バックアップ/復元の問題',
      'feedback_cat_other': 'その他',
      'please_enter_name': '名前を入力してください',
      'please_enter_amount': '金額を入力してください',
      'invalid_amount': '無効な金額',
      'confirm_delete': '削除してもよろしいですか？',
      'confirm_clear_all': 'すべてのデータを削除しますか？元に戻せません。',
      'analysis': '支出分析',
      'this_month_short': '今月',
      'two_months': '2ヶ月',
      'half_year': '6ヶ月',
      'invest_overview': 'ポートフォリオ',
      'total_value': '評価額合計',
      'total_cost': '取得原価',
      'total_profit': '損益',
      'holding_detail': '保有銘柄',
      'no_holdings': '保有銘柄なし',
      'add_first_invest': '右上の + をタップして最初の投資を追加',
      'invest_disclaimer': '本機能は個人記録・情報整理用です。投資助言ではありません。投資はご自身の判断で。',
      'shares': '株数',
      'current_price': '現在値',
      'current_value_label': '評価額',
      'est_profit': '推定損益',
      'buy_date': '購入日',
      'buy_reason': '購入理由',
      'sell_strategy': '売却戦略',
      'set_fx_rate': '為替レート設定',
      'no_current_price': '現在値なし',
      'query_price': '現在値を取得',
      'broker': '証券会社',
      'no_accounts_invest_hint': '口座がありません。「管理」で追加してください',
      'fixed_rate_03': '0.3%（固定）',
      'personal_account': 'アカウント',
      'sign_in_gmail': 'Gmailでサインイン',
      'backup_description': 'データのバックアップ・最新機能の通知',
      'google_signin': 'Googleでサインイン',
      'signin_optional': 'ログインは任意です',
      'confirm_logout': 'ログアウトの確認',
      'logout_note': 'ログアウトしてもローカルデータには影響しません。',
      'logout': 'ログアウト',
      'receive_updates': '更新情報を受け取る',
      'receive_updates_subtitle': '新機能の案内を不定期配信、いつでも解除可能',
      'restore_legacy_warning': '⚠ 旧形式のバックアップを復元しました。このバックアップには口座・投資データは含まれません。口座はクリアされました。再作成または手動で残高を修正してください。',
      'restore_success_msg': '✓ 復元完了：支出 {expenses} 件、口座 {accounts} 件、保有銘柄 {holdings} 件',
      'year_label': '{year}年',
      'month_label': '{month}月',
      'onboarding_rewatch_notice': '「ヘルプ＆サポート」からいつでもツアーを再視聴できます',
      'backup_list_item': '支出 {expenses} 件・固定費 {fixed} 件',
      'delete_this_backup': 'バックアップを削除',
      'shares_value': '{n} 株',
      'fee_and_tax_note': '手数料 {fee}%＋税 0.3% 控除後',
      'edit_account': '口座を編集',
      'add_account': '口座を追加',
      'account_settings': '口座設定',
      'custom_name': 'カスタム名',
      'balance': '残高',
      'current_balance': '現在の残高',
      'currency': '通貨',
      'count_in_total': '純資産に含める',
      'edit_entry': '記録を編集',
      'add_income': '収入を追加',
      'type_label': '種別',
      'account_label': '口座',
      'today': '今日',
      'yesterday': '昨日',
      'day_before_yesterday': '一昨日',
      'income_category': '収入カテゴリー',
      'expense_category': '支出カテゴリー',
      'recommended_items': '{category} おすすめ',
      'income_detail': '収入詳細',
      'expense_detail': '支出詳細',
      'note_optional': 'メモ（任意）',
      'update_entry': '記録を更新',
      'save_income': '収入を保存',
      'save_expense': '支出を保存',
      'name_hint': '項目名',
      'edit_holding': '保有株を編集',
      'add_investment': '投資を追加',
      'select_market': '市場を選択',
      'tw_stocks': '🇹🇼  台湾株',
      'us_stocks': '🇺🇸  米国株',
      'code_section_tw': 'コード（例：2330、0050）',
      'code_section_us': 'コード（例：AAPL、TSLA）',
      'code_input_hint_tw': 'コードまたは名称を入力',
      'broker_fee_section_tw': '証券会社と手数料（台湾株）',
      'broker_fee_section_us': '証券会社と手数料（米国株）',
      'fee_label_fmt': '手数料 {fee}',
      'fee_rate': '手数料',
      'tx_tax': '取引税',
      'trade_info': '取引情報',
      'auto_fill': '自動入力',
      'purchase_date': '購入日',
      'linked_account_optional': '口座を紐付ける（任意）',
      'unlinked': '紐付けなし',
      'account_deduct_note': '購入時に総コストが口座から差引かれ、削除時に返金されます。',
      'invest_notes_optional': '投資メモ（任意）',
      'sell_timing': '売却タイミング',
      'buy_reason_hint': '例：AIトレンドに注目',
      'sell_timing_hint': '例：+30%で半分売却',
      'broker_hint_tw': '証券会社名を入力',
      'enter_stock_code': '銘柄コードを入力してください',
      'enter_valid_shares': '有効な株数を入力してください',
      'enter_valid_cost': '有効なコストを入力してください',
      'stock_not_found': '「{code}」が見つかりません。コードを確認してください。',
      'this_bimonth': '隔月',
      'this_half_year': '半年',
      'deleted_item': '「{name}」を削除しました',
      'deleted_holding': '{code}を削除しました',
      'copy_suffix': '（コピー）',
      'price_fetch_failed': '株価を取得できません。接続を確認してください。',
      'price_updated_all': '{n}件の株価を更新しました',
      'price_updated_partial': '{updated}/{total}件の株価を更新しました',
      'streak_record_daily': '毎日記録して連続記録を維持しよう',
      'period_spending_prefix': '{period}の合計支出 ',
      'vs_last_period': '、前期比',
      'spending_increased': '増加',
      'spending_decreased': '減少',
      'app_tagline': 'お金の管理を、もっと簡単に',
      'sign_in_google': 'Googleでサインイン',
      'continue_as_guest': 'ゲストとして続ける',
      'local_data_note': 'Googleサインインは任意です。すべてのデータはデバイスに保存されます。',
      'welcome_user': 'ようこそ、{name}！',
      'onboard_skip': 'スキップ',
      'onboard_next': '次へ',
      'tour_skip': 'ツアーをスキップ',
      'tour_prev': '戻る',
      'tour_next': '次へ',
      'tour_done': '完了 ✓',
      'tour_s0_title': 'ようこそ、マネーマネージャーへ 👋',
      'tour_s0_body': 'このアプリで個人の財務管理と投資追跡を簡単に。ガイドに従って主な機能を学びましょう！',
      'tour_s1_title': '月切替',
      'tour_s1_body': '月を選択してその月の記帳データをすばやく切り替えます。',
      'tour_s2_title': '予算の進捗',
      'tour_s2_body': '今月の支出割合、残予算、推奨日割りを表示。「固定費を含む」を切り替えられます。',
      'tour_s3_title': '支出分析',
      'tour_s3_body': 'ドーナツグラフでカテゴリ別支出を表示。今月/隔月/半年を切替え前期と比較可能。カテゴリ行をタップして明細を絞り込み。',
      'tour_s4_title': '支出追加',
      'tour_s4_body': 'メインの追加ボタン！記帳タブで支出、投資タブで持株、管理タブで固定費を追加できます。',
      'tour_s4_hint': '👉 下のゴールドボタンをタップして支出を追加してみましょう',
      'tour_s5_title': '支出明細',
      'tour_s5_body': 'すべての支出記録を一覧表示。カテゴリでフィルタリングして特定タイプを検索できます。',
      'tour_s6_title': '長押しで編集・削除',
      'tour_s6_body': '支出を長押しすると編集・コピー・削除が可能。左スワイプで素早く削除することもできます。',
      'tour_s6_hint': '👉 下のレコードを長押ししてメニューを試してみましょう',
      'tour_s7_title': '投資追跡',
      'tour_s7_body': '台湾株と米国株に対応したポートフォリオ管理。台湾ドルに自動換算してリアルタイムで損益を計算。',
      'tour_s8_title': 'リアルタイム価格更新',
      'tour_s8_body': 'このボタンをタップしてYahoo Financeから最新価格を取得。すべての持株の損益が即座に更新されます。',
      'tour_s9_title': '持株追加',
      'tour_s9_body': '投資タブで＋ボタンをタップして持株を追加。銘柄コードで検索して名前と現在価格を自動入力。',
      'tour_s9_hint': '👉 下のゴールドボタンをタップして持株を追加してみましょう',
      'tour_s10_title': '管理ページ',
      'tour_s10_body': '管理タブには口座管理、予算設定、バックアップ/エクスポート、フィードバック機能があります。',
      'tour_s11_title': '口座管理',
      'tour_s11_body': '多通貨対応の普通預金口座とクレジットカードを管理。純資産を自動計算します。',
      'tour_s12_title': '固定費',
      'tour_s12_body': '毎月の固定費（家賃、サブスクなど）を設定し、分割払い回数を追跡できます。',
      'tour_s13_title': 'バックアップ＆エクスポート',
      'tour_s13_body': 'すべてのデータをローカルにバックアップするか、CSV/Excelでエクスポートして分析に活用。定期バックアップを推奨！',
      'tour_s14_title': 'フィードバック',
      'tour_s14_body': '問題や機能の提案がありますか？ここをタップして教えてください — すべてのフィードバックが改善につながります。',
      'tour_s14_hint': '👉 ここをタップしてフィードバックを試してみましょう',
      'tour_s15_title': 'ツアー完了！🎉',
      'tour_s15_body': 'マネーマネージャーの主な機能を学びました。家計管理を始めましょう！ここからいつでもツアーを再視聴できます。',
      'slide1_title': 'ようこそ\nマネーマネージャーへ',
      'slide1_subtitle': 'ここから財務管理を始めましょう',
      'slide1_intro': '1分間で主な機能をご説明します',
      'slide2_title': '支出を簡単に記録',
      'slide2_subtitle': 'カテゴリ管理と円グラフで支出を把握。',
      'slide2_f1_title': 'すばやく追加',
      'slide2_f1_desc': '中央の + ボタンで瞬時に記録',
      'slide2_f2_title': '連続記録',
      'slide2_f2_desc': '毎日の記録で良い習慣を作ろう',
      'slide2_f3_title': '全文検索',
      'slide2_f3_desc': '支出記録をすぐに検索',
      'slide3_title': 'スマートな月次予算',
      'slide3_subtitle': '月次予算を設定し、残高をリアルタイムで追跡。',
      'slide3_f1_title': '予算進捗',
      'slide3_f1_desc': '使用割合と残高をリアルタイム表示',
      'slide3_f2_title': '1日の目安支出',
      'slide3_f2_desc': '1日に使える金額を自動計算',
      'slide3_f3_title': '固定費を含む',
      'slide3_f3_desc': '月次固定費を予算計算に含められます',
      'slide4_title': 'ポートフォリオを追跡',
      'slide4_subtitle': '保有株、コスト、損益を記録。台湾株・米国株に対応。',
      'slide4_f1_title': 'リアルタイム価格',
      'slide4_f1_desc': 'ワンタップで台湾・米国株価を更新',
      'slide4_f2_title': '多通貨対応',
      'slide4_f2_desc': 'TWD/USD 損益を自動換算',
      'slide4_f3_title': '購入理由と戦略',
      'slide4_f3_desc': '購入理由と出口戦略を記録',
      'slide5_title': '財務を総合管理',
      'slide5_subtitle': '固定費、口座管理、バックアップ、すべて一か所で。',
      'slide5_f1_title': '固定費',
      'slide5_f1_desc': '家賃、サブスクなど月次固定費を一度設定',
      'slide5_f2_title': '口座管理',
      'slide5_f2_desc': '複数口座・多通貨で純資産をリアルタイム把握',
      'slide5_f3_title': 'バックアップと書き出し',
      'slide5_f3_desc': 'データバックアップとCSV/Excel書き出し',
      'slide6_title': '準備完了！',
      'slide6_subtitle': '以下のステップを完了して財務管理を始めましょう。',
      'slide6_check1': '家計簿機能を確認',
      'slide6_check2': '予算管理を確認',
      'slide6_check3': '投資追跡を確認',
      'slide6_check4': '初めての支出を追加',
      'slide6_cta_enter': 'アプリへ',
      'tour0_title': 'ようこそマネーマネージャーへ 👋',
      'tour0_body': 'このアプリで個人財務管理や投資追跡が簡単に。ツアーで主な機能をご確認ください！',
      'tour1_title': '月の切り替え',
      'tour1_body': '月を選んで、その月の家計データを素早く確認。',
      'tour2_title': '予算進捗',
      'tour2_body': '今月の支出割合、残予算、1日の推奨支出を表示。固定費を含むかどうかを切り替えられます。',
      'tour3_title': '支出分析',
      'tour3_body': 'ドーナツグラフでカテゴリ別支出を表示。月・2ヶ月・半年で切り替え可能。カテゴリをタップで絞り込み。',
      'tour4_title': '支出を追加',
      'tour4_body': 'メイン追加ボタン！家計簿ページでは支出追加、投資ページでは株追加、管理ページでは固定費追加に使います。',
      'tour4_hint': '👉 下の金色ボタンをタップして支出を追加してみましょう',
      'tour5_title': '支出明細',
      'tour5_body': 'すべての支出記録が一覧表示されます。カテゴリでフィルタリングできます。',
      'tour6_title': '長押しで編集・削除',
      'tour6_body': '支出を長押しして編集・コピー・削除。左スワイプで素早く削除できます。',
      'tour6_hint': '👉 下の記録を長押ししてメニューを試してみましょう',
      'tour7_title': '投資追跡',
      'tour7_body': 'ポートフォリオを管理。台湾・米国株対応、TWD自動換算でリアルタイム損益計算。',
      'tour8_title': '株価リアルタイム更新',
      'tour8_body': 'このボタンをタップしてYahoo Financeから最新株価を取得し、全保有株の損益を即座に更新。',
      'tour9_title': '保有株を追加',
      'tour9_body': '投資ページの + をタップして保有株を追加。銘柄コードを検索すると名前と株価が自動入力されます。',
      'tour9_hint': '👉 下の金色ボタンをタップして保有株を追加してみましょう',
      'tour10_title': '管理ページ',
      'tour10_body': '「管理」タブには口座管理、予算設定、バックアップ/書き出し、フィードバックなどが含まれます。',
      'tour11_title': '口座管理',
      'tour11_body': '複数通貨で貯蓄口座とクレジットカードを管理。純資産は自動計算されます。',
      'tour12_title': '固定費',
      'tour12_body': '月次固定費（家賃、サブスクなど）を設定し、分割払いの残りを自動追跡。',
      'tour13_title': 'バックアップと書き出し',
      'tour13_body': '全データをローカルにバックアップ、またはCSV/Excelにエクスポート。定期バックアップを推奨！',
      'tour14_title': 'フィードバック',
      'tour14_body': '問題を見つけたり、機能を提案したい場合はここをタップ。すべてのフィードバックが改善の力になります。',
      'tour14_hint': '👉 ここをタップしてフィードバックフォームを開いてみましょう',
      'tour15_title': 'ツアー完了！🎉',
      'tour15_body': 'マネーマネージャーの主な機能を理解しました。家計管理を始めましょう！いつでもここからツアーを再視聴できます。',
      'validate_title_empty': '支出名を入力してください',
      'validate_title_long': '名前は50文字以内にしてください',
      'validate_amount_empty': '金額を入力してください',
      'validate_amount_nan': '金額は数字で入力してください',
      'validate_amount_zero': '金額は0より大きくしてください',
      'validate_amount_large': '金額が大きすぎます',
      'validate_note_long': 'メモは200文字以内にしてください',
      'validate_category_empty': 'カテゴリを選択してください',
      'validate_date_range': '開始日は終了日より後にできません',
      'validate_budget_empty': '予算金額を入力してください',
      'validate_budget_nan': '予算は数字で入力してください',
      'validate_budget_zero': '予算は0より大きくしてください',
      'validate_fixed_name_empty': '項目名を入力してください',
      'validate_fixed_name_long': '名前は50文字以内にしてください',
      'validate_search_long': '検索語は100文字以内にしてください',
      'error_permission': 'この操作を実行する権限がありません',
      'error_network': 'ネットワーク接続に失敗しました。接続を確認してください。',
      'error_database': 'データベースエラーが発生しました。後でもう一度お試しください。',
      'error_generic': 'エラーが発生しました。後でもう一度お試しください。',
      'error_unknown': '不明なエラー',
    },
  };

  static String getLocaleKey(Locale locale) =>
      '${locale.languageCode}_${locale.countryCode}';

  static String translate(Locale locale, String key) {
    final k = getLocaleKey(locale);
    final map = _strings[k] ?? _strings['zh_TW']!;
    return map[key] ?? _strings['zh_TW']![key] ?? key;
  }

  static String of(BuildContext context, String key) =>
      translate(Localizations.localeOf(context), key);

  static String ofParam(
      BuildContext context, String key, Map<String, dynamic> params) {
    String str = of(context, key);
    params.forEach((k, v) => str = str.replaceAll('{$k}', v.toString()));
    return str;
  }

  static String translateParam(
      Locale locale, String key, Map<String, dynamic> params) {
    String str = translate(locale, key);
    params.forEach((k, v) => str = str.replaceAll('{$k}', v.toString()));
    return str;
  }

  // Maps zh_TW category name (stored in DB) to current locale
  static final Map<String, String> _categoryKeyMap = {
    '餐飲': 'dining', '饮食': 'dining',
    '教育': 'education',
    '娛樂': 'entertainment', '娱乐': 'entertainment',
    '交通': 'transport',
    '購物': 'shopping', '购物': 'shopping',
    '醫療': 'medical', '医疗': 'medical',
    '住居': 'living',
    '其他': 'other',
    '薪資': 'salary', '薪资': 'salary',
    '獎金': 'bonus', '奖金': 'bonus',
    '投資': 'invest_income', '投资': 'invest_income',
    '退款': 'refund',
    '其他收入': 'other_income',
  };

  static String translateCategory(BuildContext context, String storedName) {
    final key = _categoryKeyMap[storedName];
    if (key == null) return storedName;
    return of(context, key);
  }

  static String formatDateForLocale(DateTime date, Locale locale) {
    try {
      Intl.defaultLocale = '${locale.languageCode}_${locale.countryCode}';
      return DateFormat.yMd().format(date);
    } catch (_) {
      return date.toString();
    }
  }
}

class AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales
      .any((l) => l.languageCode == locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations();

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}
