import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

class AppLocalizations {
  static const supportedLocales = [
    Locale('zh', 'TW'),
    Locale('zh', 'CN'),
    Locale('en', 'US'),
    Locale('ja', 'JP'),
  ];

  static const defaultLocale = Locale('zh', 'TW');

  static const Map<String, Map<String, String>> _strings = {
    'zh_TW': {
      'app_name': '錢錢管家',
      'dashboard': '記帳',
      'detail': '明細',
      'invest': '投資',
      'manage': '管理',
      'yes': '是',
      'no': '否',
      'confirm': '確認',
      'cancel': '取消',
      'save': '保存',
      'save_label': '儲存',
      'delete': '刪除',
      'edit': '編輯',
      'add': '新增',
      'search': '搜索',
      'back': '返回',
      'close': '關閉',
      'update': '更新',
      'all': '全部',
      'loading': '加載中...',
      'error': '錯誤',
      'success': '成功',
      'warning': '警告',
      'no_data': '暫無數據',
      'copy': '複製',
      'undo': '復原',
      'no_records': '沒有記錄',
      'edited_label': '已編輯',
      'no_note': '無備註',
      'view_more': '查看更多',
      'filter_category': '分類',
      'clear_filter': '清除',
      'my_accounts': '我的帳戶',
      'net_assets': '淨資產',
      'assets': '資產',
      'liabilities': '負債',
      'accounts': '賬戶',
      'savings_accounts': '儲蓄帳戶',
      'credit_accounts': '信用帳戶',
      'no_accounts': '還沒有帳戶',
      'add_first_account': '點右上角 + 新增第一個帳戶',
      'confirm_delete_title': '確認刪除',
      'account_type': '帳戶類型',
      'please_select_account_type': '請選擇帳戶類型',
      'please_select': '請選擇',
      'dark_mode': '深色模式',
      'dark_mode_subtitle': '切換深色/淺色介面',
      'language': '語言 / Language',
      'monthly_budget': '月預算',
      'budget_updated': '✓ 預算已更新',
      'budget_progress': '預算進度',
      'remaining_budget': '剩餘預算',
      'daily_avg': '日均支出',
      'recommended_daily': '建議日均',
      'include_fixed': '含固定開銷',
      'prev_month': '上月',
      'this_month': '本月',
      'next_month': '下月',
      'current_month_label': '目前月份',
      'current_month_viewing': '查看：{year}年{month}月',
      'annual_overview_title': '{year} 年度總覽',
      'annual_expense': '年度支出',
      'annual_budget': '年度預算',
      'monthly_expense_chart': '各月支出',
      'year_annual': '年度',
      'no_expense_this_month': '本月尚無支出紀錄',
      'transactions': '筆消費',
      'budget_progress_label': '{date} 預算進度',
      'streak_active': '連續記帳 {n} 天',
      'streak_inactive': '今天還沒記帳（{n} 天）',
      'add_expense': '新增支出',
      'edit_expense': '編輯支出',
      'expense_type': '支出',
      'income': '收入',
      'expense_name': '項目名稱',
      'amount': '金額',
      'date': '日期',
      'category': '分類',
      'note': '備註',
      'optional': '選填',
      'other_date': '其他日期',
      'unlinked_account': '不關聯帳戶',
      'no_balance_effect': '不影響餘額',
      'no_accounts_hint': '請先在「管理」頁新增帳戶',
      'dining': '餐飲',
      'education': '教育',
      'entertainment': '娛樂',
      'transport': '交通',
      'shopping': '購物',
      'medical': '醫療',
      'living': '住居',
      'other': '其他',
      'salary': '薪資',
      'bonus': '獎金',
      'invest_income': '投資',
      'refund': '退款',
      'other_income': '其他收入',
      'fixed_expenses': '固定開銷',
      'add_fixed': '新增固定開銷',
      'add_fixed_hint': '點右上角 + 新增固定開銷',
      'monthly': '每月',
      'yearly': '每年',
      'active': '啟用',
      'inactive': '已停用',
      'period_unit': '期',
      'please_fill_name_amount': '請填寫名稱和金額',
      'please_enter_valid_periods': '請輸入有效的期數',
      'edit_fixed': '編輯固定開銷',
      'basic_info': '基本資訊',
      'name_label': '名稱',
      'fixed_name_hint': '例如：房貸、Netflix',
      'monthly_amount': '每月金額',
      'time_settings': '時間設定',
      'start_month': '開始月份',
      'set_periods': '設定期數',
      'total_periods': '總期數',
      'end_month': '結束月份',
      'current_progress': '目前進度',
      'progress_fmt': '第 {current} 期・已繳 {done} 期・剩 {remaining} 期',
      'notes_optional': '備註（選填）',
      'fixed_notes_hint': '例如：土地銀行房貸，利率 1.78%',
      'backup': '備份',
      'restore': '恢復',
      'export': '導出',
      'backup_data': '備份資料',
      'restore_backup': '恢復備份',
      'export_csv': '匯出 CSV',
      'export_excel': '匯出 Excel',
      'backup_export': '備份與匯出',
      'danger_zone': '危險區',
      'clear_all_expenses': '清除所有支出記錄',
      'clear_all_confirm_title': '確定清除？',
      'clear_all_confirm_content': '所有支出記錄將被永久刪除，無法還原。',
      'all_cleared': '所有記錄已清除',
      'no_backup': '尚無備份檔案',
      'select_backup': '選擇備份',
      'delete_backup_title': '刪除備份？',
      'delete_backup_confirm': '刪除後無法復原，確定要刪除此備份嗎？',
      'backup_deleted': '備份已刪除',
      'delete_failed': '刪除失敗，請稍後再試',
      'no_backup_data': '目前沒有備份資料',
      'confirm_restore_title': '確定還原？',
      'confirm_restore_content': '現有所有資料（支出、固定開銷、帳戶、投資）將被備份內容完整取代，此操作無法還原。',
      'restore_label': '還原',
      'select_month': '選擇月份',
      'backup_success': '✓ 備份成功',
      'restore_success': '✓ 恢復成功',
      'export_success': '✓ 導出成功',
      'backup_saved': '✓ 備份已儲存：{filename}',
      'backup_failed_msg': '備份失敗：{error}',
      'csv_exported': '✓ CSV 已匯出：{filename}',
      'excel_exported': '✓ Excel 已匯出：{filename}',
      'export_failed_msg': '匯出失敗：{error}',
      'expense_records': '支出記錄',
      'restore_failed_msg': '還原失敗：{error}',
      'fixed_monthly_total': '每月 NT\$ {amount}',
      'accounts_count': '{n} 個帳戶',
      'holdings_count': '{n} 檔',
      'count_unit': '{n} 個',
      'periods_completed': '已完成全部 {n} 期',
      'periods_remaining_label': '剩 {n} 期',
      'welcome_name': '歡迎，{name}！',
      'delete_confirm_account': '確定要刪除「{name}」嗎？',
      'search_hint': '搜索支出、固定開銷...',
      'no_results': '沒有找到結果',
      'search_prompt': '輸入搜索詞開始',
      'date_range': '日期範圍',
      'select_start_date': '選擇開始日期',
      'select_end_date': '選擇結束日期',
      'select_category': '選擇分類',
      'done': '完成',
      'help_support': '說明與支援',
      'rewatch_tour': '重新觀看新手導覽',
      'rewatch_tour_subtitle': '再次查看錢錢管家的主要功能與使用方式',
      'report_issue': '回報問題與建議',
      'report_issue_subtitle': '問題回報、功能建議或使用感受',
      'confirm_image': '確認附圖內容',
      'confirm_image_content': '請確認截圖中沒有不想提供的個人資訊，例如身分證字號、銀行帳號、信用卡號、密碼或其他敏感資料。',
      'confirm_submit': '確認送出',
      'feedback_sent': '已送出，謝謝你的回饋。我們會持續改善錢錢管家。',
      'feedback_failed': '送出失敗，請稍後再試。你也可以直接來信 hello@qoryva.com。',
      'feedback_intro': '遇到問題、功能建議或使用感受，都可以在這裡告訴我們。若方便，也可以附上截圖協助我們判斷。',
      'feedback_type': '回饋類型',
      'select_feedback_type': '請選擇回饋類型',
      'issue_description': '問題描述',
      'issue_description_hint': '請描述你遇到的狀況、操作步驟，或希望新增的功能。',
      'please_fill_issue': '請填寫問題描述',
      'please_enter_min_10': '請至少輸入 10 個字',
      'contact_email': '聯絡 Email',
      'contact_email_hint': '如果希望我們回覆你，請留下 Email',
      'invalid_email': 'Email 格式不正確',
      'attach_images': '附加圖片（選填，最多 3 張）',
      'submit': '送出',
      'feedback_legal_note': '請不要在回饋內容中填寫身分證字號、銀行帳號、信用卡號、密碼或其他敏感資料。送出後，我們會使用你提供的內容協助排查問題與改善服務。',
      'feedback_cat_usage': '使用問題',
      'feedback_cat_feature': '功能建議',
      'feedback_cat_data': '資料異常',
      'feedback_cat_invest': '投資頁問題',
      'feedback_cat_backup': '備份 / 還原問題',
      'feedback_cat_other': '其他',
      'please_enter_name': '請填寫名稱',
      'please_enter_amount': '請填寫金額',
      'invalid_amount': '金額無效',
      'confirm_delete': '確定要刪除嗎？',
      'confirm_clear_all': '確定要清除所有數據嗎？此操作無法撤銷。',
      'analysis': '支出分析',
      'this_month_short': '本月',
      'two_months': '雙月',
      'half_year': '半年',
      'invest_overview': '投資總覽',
      'total_value': '總現值',
      'total_cost': '總成本',
      'total_profit': '總損益',
      'holding_detail': '持股明細',
      'no_holdings': '還沒有持股',
      'add_first_invest': '點右上角 + 新增第一筆投資',
      'invest_disclaimer': '投資功能僅供個人紀錄與資訊整理使用，不構成投資建議。投資有風險，請自行判斷。',
      'shares': '股數',
      'current_price': '現價',
      'current_value_label': '現值',
      'est_profit': '預估損益',
      'buy_date': '買入日期',
      'buy_reason': '買入理由',
      'sell_strategy': '出場策略',
      'set_fx_rate': '設定匯率',
      'no_current_price': '尚無現價',
      'query_price': '查詢現價',
      'broker': '券商',
      'no_accounts_invest_hint': '尚未建立帳戶，可在「管理」頁新增',
      'fixed_rate_03': '0.3%（固定）',
      'personal_account': '個人帳號',
      'sign_in_gmail': '使用 Gmail 登入',
      'backup_description': '備份資料 · 接收最新功能通知',
      'google_signin': 'Google 登入',
      'signin_optional': '登入為選填，不影響 App 功能',
      'confirm_logout': '確認登出',
      'logout_note': '登出後不影響本機資料。',
      'logout': '登出',
      'receive_updates': '接收最新消息與功能更新',
      'receive_updates_subtitle': '不定期發送新功能介紹，可隨時關閉',
      'restore_legacy_warning': '⚠ 舊版備份已還原。此備份不含帳戶與投資資料，帳戶已清空，請重新建立或手動校正餘額。',
      'restore_success_msg': '✓ 已還原 {expenses} 筆支出、{accounts} 個帳戶、{holdings} 筆持股',
      'year_label': '{year} 年',
      'month_label': '{month}月',
      'onboarding_rewatch_notice': '可隨時在「說明與支援」重新觀看導覽',
      'backup_list_item': '{expenses} 筆支出・{fixed} 項固定開銷',
      'delete_this_backup': '刪除此備份',
      'shares_value': '{n} 股',
      'fee_and_tax_note': '已扣手續費 {fee}%＋交易稅 0.3%',
      'edit_account': '編輯帳戶',
      'add_account': '新建帳戶',
      'account_settings': '帳戶設定',
      'custom_name': '自訂名稱',
      'balance': '餘額',
      'current_balance': '當前餘額',
      'currency': '貨幣',
      'count_in_total': '計入總資產',
      'edit_entry': '編輯記帳',
      'add_income': '新增收入',
      'type_label': '類型',
      'account_label': '帳戶',
      'today': '今天',
      'yesterday': '昨天',
      'day_before_yesterday': '前天',
      'income_category': '收入類別',
      'expense_category': '支出類別',
      'recommended_items': '{category} 推薦項目',
      'income_detail': '收入明細',
      'expense_detail': '支出明細',
      'note_optional': '備註（選填）',
      'update_entry': '更新記帳',
      'save_income': '儲存收入',
      'save_expense': '儲存支出',
      'name_hint': '項目名稱',
      'edit_holding': '編輯持股',
      'add_investment': '新增投資',
      'select_market': '選擇市場',
      'tw_stocks': '🇹🇼  台股',
      'us_stocks': '🇺🇸  美股',
      'code_section_tw': '股票代碼（例：2330、0050）',
      'code_section_us': '股票代碼（例：AAPL、TSLA）',
      'code_input_hint_tw': '輸入代碼或名稱',
      'broker_fee_section_tw': '券商與手續費（台股）',
      'broker_fee_section_us': '券商與手續費（美股）',
      'fee_label_fmt': '手續費 {fee}',
      'fee_rate': '手續費',
      'tx_tax': '交易稅',
      'trade_info': '交易資訊',
      'auto_fill': '自動帶入',
      'purchase_date': '購買日期',
      'linked_account_optional': '關聯帳戶（選填）',
      'unlinked': '不關聯',
      'account_deduct_note': '買入時將從帳戶扣除總成本；刪除持股時將退回金額',
      'invest_notes_optional': '投資筆記（選填）',
      'sell_timing': '賣出時機',
      'buy_reason_hint': '例如：看好 AI 趨勢',
      'sell_timing_hint': '例如：漲 30% 賣出一半',
      'broker_hint_tw': '輸入券商名稱',
      'enter_stock_code': '請輸入股票代碼',
      'enter_valid_shares': '請輸入有效的股數',
      'enter_valid_cost': '請輸入有效的成本',
      'stock_not_found': '找不到「{code}」，請確認代碼是否正確',
      'this_bimonth': '本雙月',
      'this_half_year': '本半年',
      'deleted_item': '已刪除「{name}」',
      'deleted_holding': '已刪除 {code}',
      'copy_suffix': '（副本）',
      'price_fetch_failed': '無法取得股價，請確認網路或稍後再試',
      'price_updated_all': '已更新 {n} 檔現價',
      'price_updated_partial': '已更新 {updated}/{total} 檔現價',
      'streak_record_daily': '每天記帳可維持連續天數',
      'period_spending_prefix': '{period}的總消費為 ',
      'vs_last_period': '，較上期',
      'spending_increased': '增加',
      'spending_decreased': '減少',
    },
    'zh_CN': {
      'app_name': '钱钱管家',
      'dashboard': '记账',
      'detail': '明细',
      'invest': '投资',
      'manage': '管理',
      'yes': '是',
      'no': '否',
      'confirm': '确认',
      'cancel': '取消',
      'save': '保存',
      'save_label': '保存',
      'delete': '删除',
      'edit': '编辑',
      'add': '新增',
      'search': '搜索',
      'back': '返回',
      'close': '关闭',
      'update': '更新',
      'all': '全部',
      'loading': '加载中...',
      'error': '错误',
      'success': '成功',
      'warning': '警告',
      'no_data': '暂无数据',
      'copy': '复制',
      'undo': '撤销',
      'no_records': '没有记录',
      'edited_label': '已编辑',
      'no_note': '无备注',
      'view_more': '查看更多',
      'filter_category': '分类',
      'clear_filter': '清除',
      'my_accounts': '我的账户',
      'net_assets': '净资产',
      'assets': '资产',
      'liabilities': '负债',
      'accounts': '账户',
      'savings_accounts': '储蓄账户',
      'credit_accounts': '信用账户',
      'no_accounts': '还没有账户',
      'add_first_account': '点右上角 + 新增第一个账户',
      'confirm_delete_title': '确认删除',
      'account_type': '账户类型',
      'please_select_account_type': '请选择账户类型',
      'please_select': '请选择',
      'dark_mode': '深色模式',
      'dark_mode_subtitle': '切换深色/浅色界面',
      'language': '语言 / Language',
      'monthly_budget': '月预算',
      'budget_updated': '✓ 预算已更新',
      'budget_progress': '预算进度',
      'remaining_budget': '剩余预算',
      'daily_avg': '日均支出',
      'recommended_daily': '建议日均',
      'include_fixed': '含固定开销',
      'prev_month': '上月',
      'this_month': '本月',
      'next_month': '下月',
      'current_month_label': '当前月份',
      'current_month_viewing': '查看：{year}年{month}月',
      'annual_overview_title': '{year} 年度总览',
      'annual_expense': '年度支出',
      'annual_budget': '年度预算',
      'monthly_expense_chart': '各月支出',
      'year_annual': '年度',
      'no_expense_this_month': '本月暂无支出记录',
      'transactions': '笔消费',
      'budget_progress_label': '{date} 预算进度',
      'streak_active': '连续记账 {n} 天',
      'streak_inactive': '今天还没记账（{n} 天）',
      'add_expense': '新增支出',
      'edit_expense': '编辑支出',
      'expense_type': '支出',
      'income': '收入',
      'expense_name': '项目名称',
      'amount': '金额',
      'date': '日期',
      'category': '分类',
      'note': '备注',
      'optional': '选填',
      'other_date': '其他日期',
      'unlinked_account': '不关联账户',
      'no_balance_effect': '不影响余额',
      'no_accounts_hint': '请先在「管理」页新增账户',
      'dining': '餐饮',
      'education': '教育',
      'entertainment': '娱乐',
      'transport': '交通',
      'shopping': '购物',
      'medical': '医疗',
      'living': '住居',
      'other': '其他',
      'salary': '薪资',
      'bonus': '奖金',
      'invest_income': '投资',
      'refund': '退款',
      'other_income': '其他收入',
      'fixed_expenses': '固定开销',
      'add_fixed': '新增固定开销',
      'add_fixed_hint': '点右上角 + 新增固定开销',
      'monthly': '每月',
      'yearly': '每年',
      'active': '启用',
      'inactive': '已停用',
      'period_unit': '期',
      'please_fill_name_amount': '请填写名称和金额',
      'please_enter_valid_periods': '请输入有效的期数',
      'edit_fixed': '编辑固定开销',
      'basic_info': '基本信息',
      'name_label': '名称',
      'fixed_name_hint': '例如：房贷、Netflix',
      'monthly_amount': '每月金额',
      'time_settings': '时间设定',
      'start_month': '开始月份',
      'set_periods': '设定期数',
      'total_periods': '总期数',
      'end_month': '结束月份',
      'current_progress': '目前进度',
      'progress_fmt': '第 {current} 期・已缴 {done} 期・剩 {remaining} 期',
      'notes_optional': '备注（选填）',
      'fixed_notes_hint': '例如：土地银行房贷，利率 1.78%',
      'backup': '备份',
      'restore': '恢复',
      'export': '导出',
      'backup_data': '备份资料',
      'restore_backup': '恢复备份',
      'export_csv': '导出 CSV',
      'export_excel': '导出 Excel',
      'backup_export': '备份与导出',
      'danger_zone': '危险区',
      'clear_all_expenses': '清除所有支出记录',
      'clear_all_confirm_title': '确定清除？',
      'clear_all_confirm_content': '所有支出记录将被永久删除，无法还原。',
      'all_cleared': '所有记录已清除',
      'no_backup': '尚无备份文件',
      'select_backup': '选择备份',
      'delete_backup_title': '删除备份？',
      'delete_backup_confirm': '删除后无法恢复，确定要删除此备份吗？',
      'backup_deleted': '备份已删除',
      'delete_failed': '删除失败，请稍后重试',
      'no_backup_data': '目前没有备份数据',
      'confirm_restore_title': '确定还原？',
      'confirm_restore_content': '现有所有数据（支出、固定开销、账户、投资）将被备份内容完整取代，此操作无法还原。',
      'restore_label': '还原',
      'select_month': '选择月份',
      'backup_success': '✓ 备份成功',
      'restore_success': '✓ 恢复成功',
      'export_success': '✓ 导出成功',
      'backup_saved': '✓ 备份已保存：{filename}',
      'backup_failed_msg': '备份失败：{error}',
      'csv_exported': '✓ CSV 已导出：{filename}',
      'excel_exported': '✓ Excel 已导出：{filename}',
      'export_failed_msg': '导出失败：{error}',
      'expense_records': '支出记录',
      'restore_failed_msg': '还原失败：{error}',
      'fixed_monthly_total': '每月 NT\$ {amount}',
      'accounts_count': '{n} 个账户',
      'holdings_count': '{n} 只',
      'count_unit': '{n} 个',
      'periods_completed': '已完成全部 {n} 期',
      'periods_remaining_label': '剩 {n} 期',
      'welcome_name': '欢迎，{name}！',
      'delete_confirm_account': '确定要删除「{name}」吗？',
      'search_hint': '搜索支出、固定开销...',
      'no_results': '没有找到结果',
      'search_prompt': '输入搜索词开始',
      'date_range': '日期范围',
      'select_start_date': '选择开始日期',
      'select_end_date': '选择结束日期',
      'select_category': '选择分类',
      'done': '完成',
      'help_support': '说明与支援',
      'rewatch_tour': '重新观看新手导览',
      'rewatch_tour_subtitle': '再次查看钱钱管家的主要功能与使用方式',
      'report_issue': '回报问题与建议',
      'report_issue_subtitle': '问题回报、功能建议或使用感受',
      'confirm_image': '确认附图内容',
      'confirm_image_content': '请确认截图中没有不想提供的个人信息，例如身份证号、银行账号、信用卡号、密码或其他敏感资料。',
      'confirm_submit': '确认送出',
      'feedback_sent': '已送出，谢谢你的回馈。我们会持续改善钱钱管家。',
      'feedback_failed': '送出失败，请稍后再试。你也可以直接来信 hello@qoryva.com。',
      'feedback_intro': '遇到问题、功能建议或使用感受，都可以在这里告诉我们。若方便，也可以附上截图协助我们判断。',
      'feedback_type': '回馈类型',
      'select_feedback_type': '请选择回馈类型',
      'issue_description': '问题描述',
      'issue_description_hint': '请描述你遇到的状况、操作步骤，或希望新增的功能。',
      'please_fill_issue': '请填写问题描述',
      'please_enter_min_10': '请至少输入 10 个字',
      'contact_email': '联系 Email',
      'contact_email_hint': '如果希望我们回复你，请留下 Email',
      'invalid_email': 'Email 格式不正确',
      'attach_images': '附加图片（选填，最多3张）',
      'submit': '送出',
      'feedback_legal_note': '请不要在回馈内容中填写身份证号、银行账号、信用卡号、密码或其他敏感资料。送出后，我们会使用你提供的内容协助排查问题与改善服务。',
      'feedback_cat_usage': '使用问题',
      'feedback_cat_feature': '功能建议',
      'feedback_cat_data': '资料异常',
      'feedback_cat_invest': '投资页问题',
      'feedback_cat_backup': '备份/还原问题',
      'feedback_cat_other': '其他',
      'please_enter_name': '请填写名称',
      'please_enter_amount': '请填写金额',
      'invalid_amount': '金额无效',
      'confirm_delete': '确定要删除吗？',
      'confirm_clear_all': '确定要清除所有数据吗？此操作无法撤销。',
      'analysis': '支出分析',
      'this_month_short': '本月',
      'two_months': '双月',
      'half_year': '半年',
      'invest_overview': '投资总览',
      'total_value': '总现值',
      'total_cost': '总成本',
      'total_profit': '总损益',
      'holding_detail': '持股明细',
      'no_holdings': '还没有持股',
      'add_first_invest': '点右上角 + 新增第一笔投资',
      'invest_disclaimer': '投资功能仅供个人记录与信息整理使用，不构成投资建议。投资有风险，请自行判断。',
      'shares': '股数',
      'current_price': '现价',
      'current_value_label': '现值',
      'est_profit': '预估损益',
      'buy_date': '买入日期',
      'buy_reason': '买入理由',
      'sell_strategy': '出场策略',
      'set_fx_rate': '设定汇率',
      'no_current_price': '尚无现价',
      'query_price': '查询现价',
      'broker': '券商',
      'no_accounts_invest_hint': '尚未建立账户，可在「管理」页新增',
      'fixed_rate_03': '0.3%（固定）',
      'personal_account': '个人账号',
      'sign_in_gmail': '使用 Gmail 登录',
      'backup_description': '备份数据 · 接收最新功能通知',
      'google_signin': 'Google 登录',
      'signin_optional': '登录为选填，不影响 App 功能',
      'confirm_logout': '确认登出',
      'logout_note': '登出后不影响本机数据。',
      'logout': '登出',
      'receive_updates': '接收最新消息与功能更新',
      'receive_updates_subtitle': '不定期发送新功能介绍，可随时关闭',
      'restore_legacy_warning': '⚠ 旧版备份已还原。此备份不含账户与投资数据，账户已清空，请重新建立或手动校正余额。',
      'restore_success_msg': '✓ 已还原 {expenses} 笔支出、{accounts} 个账户、{holdings} 笔持股',
      'year_label': '{year} 年',
      'month_label': '{month}月',
      'onboarding_rewatch_notice': '可随时在「说明与支援」重新观看导览',
      'backup_list_item': '{expenses} 笔支出·{fixed} 项固定开销',
      'delete_this_backup': '删除此备份',
      'shares_value': '{n} 股',
      'fee_and_tax_note': '已扣手续费 {fee}%＋交易税 0.3%',
      'edit_account': '编辑账户',
      'add_account': '新建账户',
      'account_settings': '账户设置',
      'custom_name': '自定义名称',
      'balance': '余额',
      'current_balance': '当前余额',
      'currency': '货币',
      'count_in_total': '计入总资产',
      'edit_entry': '编辑记账',
      'add_income': '新增收入',
      'type_label': '类型',
      'account_label': '账户',
      'today': '今天',
      'yesterday': '昨天',
      'day_before_yesterday': '前天',
      'income_category': '收入类别',
      'expense_category': '支出类别',
      'recommended_items': '{category} 推荐项目',
      'income_detail': '收入明细',
      'expense_detail': '支出明细',
      'note_optional': '备注（选填）',
      'update_entry': '更新记账',
      'save_income': '保存收入',
      'save_expense': '保存支出',
      'name_hint': '项目名称',
      'edit_holding': '编辑持股',
      'add_investment': '新增投资',
      'select_market': '选择市场',
      'tw_stocks': '🇹🇼  台股',
      'us_stocks': '🇺🇸  美股',
      'code_section_tw': '股票代码（例：2330、0050）',
      'code_section_us': '股票代码（例：AAPL、TSLA）',
      'code_input_hint_tw': '输入代码或名称',
      'broker_fee_section_tw': '券商与手续费（台股）',
      'broker_fee_section_us': '券商与手续费（美股）',
      'fee_label_fmt': '手续费 {fee}',
      'fee_rate': '手续费',
      'tx_tax': '交易税',
      'trade_info': '交易信息',
      'auto_fill': '自动带入',
      'purchase_date': '购买日期',
      'linked_account_optional': '关联账户（选填）',
      'unlinked': '不关联',
      'account_deduct_note': '买入时将从账户扣除总成本；删除持股时将退回金额',
      'invest_notes_optional': '投资笔记（选填）',
      'sell_timing': '卖出时机',
      'buy_reason_hint': '例如：看好 AI 趋势',
      'sell_timing_hint': '例如：涨 30% 卖出一半',
      'broker_hint_tw': '输入券商名称',
      'enter_stock_code': '请输入股票代码',
      'enter_valid_shares': '请输入有效的股数',
      'enter_valid_cost': '请输入有效的成本',
      'stock_not_found': '找不到"{code}"，请确认代码是否正确',
      'this_bimonth': '本双月',
      'this_half_year': '本半年',
      'deleted_item': '已删除「{name}」',
      'deleted_holding': '已删除 {code}',
      'copy_suffix': '（副本）',
      'price_fetch_failed': '无法获取股价，请确认网路或稍后再试',
      'price_updated_all': '已更新 {n} 档现价',
      'price_updated_partial': '已更新 {updated}/{total} 档现价',
      'streak_record_daily': '每天记账可维持连续天数',
      'period_spending_prefix': '{period}的总消费为 ',
      'vs_last_period': '，较上期',
      'spending_increased': '增加',
      'spending_decreased': '减少',
    },
    'en_US': {
      'app_name': 'Money Manager',
      'dashboard': 'Budget',
      'detail': 'Details',
      'invest': 'Invest',
      'manage': 'Manage',
      'yes': 'Yes',
      'no': 'No',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'save': 'Save',
      'save_label': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'search': 'Search',
      'back': 'Back',
      'close': 'Close',
      'update': 'Update',
      'all': 'All',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'warning': 'Warning',
      'no_data': 'No data',
      'copy': 'Duplicate',
      'undo': 'Undo',
      'no_records': 'No records',
      'edited_label': 'Edited',
      'no_note': 'No note',
      'view_more': 'View More',
      'filter_category': 'Category',
      'clear_filter': 'Clear',
      'my_accounts': 'My Accounts',
      'net_assets': 'Net Assets',
      'assets': 'Assets',
      'liabilities': 'Liabilities',
      'accounts': 'Accounts',
      'savings_accounts': 'Savings',
      'credit_accounts': 'Credit',
      'no_accounts': 'No accounts yet',
      'add_first_account': 'Tap + to add your first account',
      'confirm_delete_title': 'Confirm Delete',
      'account_type': 'Account Type',
      'please_select_account_type': 'Please select account type',
      'please_select': 'Please select',
      'dark_mode': 'Dark Mode',
      'dark_mode_subtitle': 'Toggle dark/light interface',
      'language': 'Language',
      'monthly_budget': 'Monthly Budget',
      'budget_updated': '✓ Budget Updated',
      'budget_progress': 'Budget Progress',
      'remaining_budget': 'Remaining',
      'daily_avg': 'Daily Avg',
      'recommended_daily': 'Recommended',
      'include_fixed': 'Inc. Fixed',
      'prev_month': 'Last',
      'this_month': 'This Month',
      'next_month': 'Next',
      'current_month_label': 'Current Month',
      'current_month_viewing': 'Viewing: {year}/{month}',
      'annual_overview_title': '{year} Annual Overview',
      'annual_expense': 'Annual Expense',
      'annual_budget': 'Annual Budget',
      'monthly_expense_chart': 'Monthly Expenses',
      'year_annual': 'Annual',
      'no_expense_this_month': 'No expenses this month',
      'transactions': 'transactions',
      'budget_progress_label': '{date} Budget',
      'streak_active': '{n}-day streak',
      'streak_inactive': 'No record today ({n} days)',
      'add_expense': 'Add Expense',
      'edit_expense': 'Edit Expense',
      'expense_type': 'Expense',
      'income': 'Income',
      'expense_name': 'Name',
      'amount': 'Amount',
      'date': 'Date',
      'category': 'Category',
      'note': 'Note',
      'optional': 'Optional',
      'other_date': 'Other date',
      'unlinked_account': 'No Account',
      'no_balance_effect': 'Balance unaffected',
      'no_accounts_hint': 'Add an account in Manage first',
      'dining': 'Dining',
      'education': 'Education',
      'entertainment': 'Entertainment',
      'transport': 'Transport',
      'shopping': 'Shopping',
      'medical': 'Medical',
      'living': 'Housing',
      'other': 'Other',
      'salary': 'Salary',
      'bonus': 'Bonus',
      'invest_income': 'Investment',
      'refund': 'Refund',
      'other_income': 'Other Income',
      'fixed_expenses': 'Fixed Expenses',
      'add_fixed': 'Add Fixed Expense',
      'add_fixed_hint': 'Tap + to add a fixed expense',
      'monthly': 'Monthly',
      'yearly': 'Yearly',
      'active': 'Active',
      'inactive': 'Inactive',
      'period_unit': 'pds',
      'please_fill_name_amount': 'Please fill in name and amount',
      'please_enter_valid_periods': 'Please enter valid period count',
      'edit_fixed': 'Edit Fixed Expense',
      'basic_info': 'Basic Info',
      'name_label': 'Name',
      'fixed_name_hint': 'e.g. Mortgage, Netflix',
      'monthly_amount': 'Monthly Amount',
      'time_settings': 'Schedule',
      'start_month': 'Start Month',
      'set_periods': 'Set Periods',
      'total_periods': 'Total Periods',
      'end_month': 'End Month',
      'current_progress': 'Progress',
      'progress_fmt': 'Period {current}・Paid {done}・Left {remaining}',
      'notes_optional': 'Notes (optional)',
      'fixed_notes_hint': 'e.g. Land Bank mortgage, rate 1.78%',
      'backup': 'Backup',
      'restore': 'Restore',
      'export': 'Export',
      'backup_data': 'Backup Data',
      'restore_backup': 'Restore Backup',
      'export_csv': 'Export CSV',
      'export_excel': 'Export Excel',
      'backup_export': 'Backup & Export',
      'danger_zone': 'Danger Zone',
      'clear_all_expenses': 'Clear All Expenses',
      'clear_all_confirm_title': 'Confirm Clear?',
      'clear_all_confirm_content': 'All expense records will be permanently deleted. This cannot be undone.',
      'all_cleared': 'All records cleared',
      'no_backup': 'No backup files',
      'select_backup': 'Select Backup',
      'delete_backup_title': 'Delete Backup?',
      'delete_backup_confirm': 'This cannot be undone. Delete this backup?',
      'backup_deleted': 'Backup deleted',
      'delete_failed': 'Delete failed, please try again',
      'no_backup_data': 'No backups available',
      'confirm_restore_title': 'Confirm Restore?',
      'confirm_restore_content': 'All existing data (expenses, fixed items, accounts, investments) will be replaced by the backup. This cannot be undone.',
      'restore_label': 'Restore',
      'select_month': 'Select Month',
      'backup_success': '✓ Backup Successful',
      'restore_success': '✓ Restore Successful',
      'export_success': '✓ Export Successful',
      'backup_saved': '✓ Backup saved: {filename}',
      'backup_failed_msg': 'Backup failed: {error}',
      'csv_exported': '✓ CSV exported: {filename}',
      'excel_exported': '✓ Excel exported: {filename}',
      'export_failed_msg': 'Export failed: {error}',
      'expense_records': 'Expense Records',
      'restore_failed_msg': 'Restore failed: {error}',
      'fixed_monthly_total': 'NT\$ {amount}/mo',
      'accounts_count': '{n} account(s)',
      'holdings_count': '{n} stock(s)',
      'count_unit': '{n}',
      'periods_completed': 'All {n} periods done',
      'periods_remaining_label': '{n} left',
      'welcome_name': 'Welcome, {name}!',
      'delete_confirm_account': 'Delete "{name}"?',
      'search_hint': 'Search expenses, fixed items...',
      'no_results': 'No results found',
      'search_prompt': 'Enter a search term to begin',
      'date_range': 'Date Range',
      'select_start_date': 'Select Start Date',
      'select_end_date': 'Select End Date',
      'select_category': 'Select Category',
      'done': 'Done',
      'help_support': 'Help & Support',
      'rewatch_tour': 'Rewatch Tutorial',
      'rewatch_tour_subtitle': 'Replay the main features tour',
      'report_issue': 'Report an Issue',
      'report_issue_subtitle': 'Bug reports, feature requests & feedback',
      'confirm_image': 'Confirm Image Content',
      'confirm_image_content': 'Please make sure the screenshot contains no personal info such as ID numbers, bank accounts, credit cards, passwords, or other sensitive data.',
      'confirm_submit': 'Confirm & Submit',
      'feedback_sent': 'Submitted! Thank you for your feedback. We\'ll keep improving the app.',
      'feedback_failed': 'Submission failed. Please try again later or email hello@qoryva.com.',
      'feedback_intro': 'Share any issues, feature ideas, or general feedback here. Screenshots are welcome to help us investigate.',
      'feedback_type': 'Feedback Type',
      'select_feedback_type': 'Select feedback type',
      'issue_description': 'Description',
      'issue_description_hint': 'Describe your issue, steps to reproduce, or the feature you\'d like to see.',
      'please_fill_issue': 'Please describe the issue',
      'please_enter_min_10': 'Please enter at least 10 characters',
      'contact_email': 'Contact Email',
      'contact_email_hint': 'Leave your email if you\'d like us to reply',
      'invalid_email': 'Invalid email format',
      'attach_images': 'Attach Images (optional, up to 3)',
      'submit': 'Submit',
      'feedback_legal_note': 'Do not include ID numbers, bank accounts, credit cards, passwords or other sensitive data in your feedback. Submitted content will be used to help diagnose issues and improve the app.',
      'feedback_cat_usage': 'Usage Issue',
      'feedback_cat_feature': 'Feature Request',
      'feedback_cat_data': 'Data Anomaly',
      'feedback_cat_invest': 'Investment Issue',
      'feedback_cat_backup': 'Backup / Restore Issue',
      'feedback_cat_other': 'Other',
      'please_enter_name': 'Please enter a name',
      'please_enter_amount': 'Please enter an amount',
      'invalid_amount': 'Invalid amount',
      'confirm_delete': 'Are you sure you want to delete?',
      'confirm_clear_all': 'Delete all data? This cannot be undone.',
      'analysis': 'Spending Analysis',
      'this_month_short': 'Month',
      'two_months': '2 Months',
      'half_year': '6 Months',
      'invest_overview': 'Portfolio',
      'total_value': 'Total Value',
      'total_cost': 'Total Cost',
      'total_profit': 'P&L',
      'holding_detail': 'Holdings',
      'no_holdings': 'No holdings yet',
      'add_first_invest': 'Tap + to add your first investment',
      'invest_disclaimer': 'For personal records only. Not investment advice. Invest at your own risk.',
      'shares': 'Shares',
      'current_price': 'Price',
      'current_value_label': 'Value',
      'est_profit': 'Est. P&L',
      'buy_date': 'Buy Date',
      'buy_reason': 'Buy Reason',
      'sell_strategy': 'Exit Strategy',
      'set_fx_rate': 'Set FX Rate',
      'no_current_price': 'No price data',
      'query_price': 'Fetch Price',
      'broker': 'Broker',
      'no_accounts_invest_hint': 'No account yet. Add one in Manage',
      'fixed_rate_03': '0.3% (fixed)',
      'personal_account': 'Account',
      'sign_in_gmail': 'Sign in with Gmail',
      'backup_description': 'Backup data · Get feature updates',
      'google_signin': 'Sign in with Google',
      'signin_optional': 'Sign-in is optional',
      'confirm_logout': 'Confirm Sign Out',
      'logout_note': 'Signing out won\'t affect local data.',
      'logout': 'Sign Out',
      'receive_updates': 'Receive updates & news',
      'receive_updates_subtitle': 'Occasional highlights, unsubscribe anytime',
      'restore_legacy_warning': '⚠ Legacy backup restored. This backup does not include account or investment data. Accounts cleared. Please recreate or adjust balances manually.',
      'restore_success_msg': '✓ Restored: {expenses} expenses, {accounts} accounts, {holdings} holdings',
      'year_label': '{year}',
      'month_label': 'M{month}',
      'onboarding_rewatch_notice': 'You can rewatch the tour anytime in Help & Support',
      'backup_list_item': '{expenses} expenses · {fixed} fixed items',
      'delete_this_backup': 'Delete backup',
      'shares_value': '{n} shares',
      'fee_and_tax_note': 'After fee {fee}% + 0.3% tax',
      'edit_account': 'Edit Account',
      'add_account': 'New Account',
      'account_settings': 'Account Settings',
      'custom_name': 'Custom Name',
      'balance': 'Balance',
      'current_balance': 'Current Balance',
      'currency': 'Currency',
      'count_in_total': 'Include in Net Assets',
      'edit_entry': 'Edit Entry',
      'add_income': 'Add Income',
      'type_label': 'Type',
      'account_label': 'Account',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'day_before_yesterday': '2 Days Ago',
      'income_category': 'Income Category',
      'expense_category': 'Expense Category',
      'recommended_items': 'Suggested: {category}',
      'income_detail': 'Income Details',
      'expense_detail': 'Expense Details',
      'note_optional': 'Note (optional)',
      'update_entry': 'Update Entry',
      'save_income': 'Save Income',
      'save_expense': 'Save Expense',
      'name_hint': 'Item name',
      'edit_holding': 'Edit Holding',
      'add_investment': 'Add Investment',
      'select_market': 'Select Market',
      'tw_stocks': '🇹🇼  Taiwan',
      'us_stocks': '🇺🇸  US Stocks',
      'code_section_tw': 'Symbol (e.g. 2330, 0050)',
      'code_section_us': 'Symbol (e.g. AAPL, TSLA)',
      'code_input_hint_tw': 'Enter code or name',
      'broker_fee_section_tw': 'Broker & Fee (TW)',
      'broker_fee_section_us': 'Broker & Fee (US)',
      'fee_label_fmt': 'Fee {fee}',
      'fee_rate': 'Fee Rate',
      'tx_tax': 'Trans. Tax',
      'trade_info': 'Trade Info',
      'auto_fill': 'Auto-filled',
      'purchase_date': 'Purchase Date',
      'linked_account_optional': 'Link Account (optional)',
      'unlinked': 'None',
      'account_deduct_note': 'Purchase cost deducted from account; refunded on deletion.',
      'invest_notes_optional': 'Investment Notes (optional)',
      'sell_timing': 'Exit Timing',
      'buy_reason_hint': 'e.g. Bullish on AI trend',
      'sell_timing_hint': 'e.g. Sell half at +30%',
      'broker_hint_tw': 'Enter broker name',
      'enter_stock_code': 'Please enter stock symbol',
      'enter_valid_shares': 'Please enter valid shares',
      'enter_valid_cost': 'Please enter valid cost',
      'stock_not_found': 'Symbol "{code}" not found. Please verify the code.',
      'this_bimonth': 'Bi-Monthly',
      'this_half_year': 'Six Months',
      'deleted_item': '"{name}" deleted',
      'deleted_holding': '{code} deleted',
      'copy_suffix': ' (Copy)',
      'price_fetch_failed': 'Failed to fetch price. Check your connection.',
      'price_updated_all': 'Updated {n} prices',
      'price_updated_partial': 'Updated {updated}/{total} prices',
      'streak_record_daily': 'Record daily to maintain your streak',
      'period_spending_prefix': 'Spending for {period}: ',
      'vs_last_period': ', vs. last period',
      'spending_increased': '↑',
      'spending_decreased': '↓',
    },
    'ja_JP': {
      'app_name': 'マネーマネージャー',
      'dashboard': '家計簿',
      'detail': '明細',
      'invest': '投資',
      'manage': '管理',
      'yes': 'はい',
      'no': 'いいえ',
      'confirm': '確認',
      'cancel': 'キャンセル',
      'save': '保存',
      'save_label': '保存',
      'delete': '削除',
      'edit': '編集',
      'add': '追加',
      'search': '検索',
      'back': '戻る',
      'close': '閉じる',
      'update': '更新',
      'all': 'すべて',
      'loading': '読み込み中...',
      'error': 'エラー',
      'success': '成功',
      'warning': '警告',
      'no_data': 'データなし',
      'copy': '複製',
      'undo': '元に戻す',
      'no_records': '記録なし',
      'edited_label': '編集済み',
      'no_note': 'メモなし',
      'view_more': '詳細を見る',
      'filter_category': 'カテゴリー',
      'clear_filter': 'クリア',
      'my_accounts': 'マイアカウント',
      'net_assets': '純資産',
      'assets': '資産',
      'liabilities': '負債',
      'accounts': '口座',
      'savings_accounts': '貯蓄口座',
      'credit_accounts': 'クレジット',
      'no_accounts': '口座がありません',
      'add_first_account': '右上の + をタップして最初の口座を追加',
      'confirm_delete_title': '削除の確認',
      'account_type': '口座タイプ',
      'please_select_account_type': '口座タイプを選択してください',
      'please_select': '選択してください',
      'dark_mode': 'ダークモード',
      'dark_mode_subtitle': 'ダーク/ライト切替',
      'language': '言語 / Language',
      'monthly_budget': '月次予算',
      'budget_updated': '✓ 予算を更新しました',
      'budget_progress': '予算進捗',
      'remaining_budget': '残予算',
      'daily_avg': '日平均支出',
      'recommended_daily': '推奨日額',
      'include_fixed': '固定費含む',
      'prev_month': '先月',
      'this_month': '今月',
      'next_month': '来月',
      'current_month_label': '今月',
      'current_month_viewing': '表示中：{year}年{month}月',
      'annual_overview_title': '{year}年 年間概要',
      'annual_expense': '年間支出',
      'annual_budget': '年間予算',
      'monthly_expense_chart': '月別支出',
      'year_annual': '年間',
      'no_expense_this_month': '今月の支出はありません',
      'transactions': '件',
      'budget_progress_label': '{date} 予算',
      'streak_active': '{n}日連続',
      'streak_inactive': '今日未記録（{n}日）',
      'add_expense': '支出を追加',
      'edit_expense': '支出を編集',
      'expense_type': '支出',
      'income': '収入',
      'expense_name': '項目名',
      'amount': '金額',
      'date': '日付',
      'category': 'カテゴリー',
      'note': 'メモ',
      'optional': '任意',
      'other_date': 'その他の日付',
      'unlinked_account': '口座なし',
      'no_balance_effect': '残高に影響しない',
      'no_accounts_hint': '先に「管理」で口座を追加してください',
      'dining': '飲食',
      'education': '教育',
      'entertainment': '娯楽',
      'transport': '交通',
      'shopping': 'ショッピング',
      'medical': '医療',
      'living': '住居',
      'other': 'その他',
      'salary': '給与',
      'bonus': 'ボーナス',
      'invest_income': '投資',
      'refund': '返金',
      'other_income': 'その他収入',
      'fixed_expenses': '固定費',
      'add_fixed': '固定費を追加',
      'add_fixed_hint': '右上の + をタップして固定費を追加',
      'monthly': '毎月',
      'yearly': '毎年',
      'active': '有効',
      'inactive': '無効',
      'period_unit': '回',
      'please_fill_name_amount': '名前と金額を入力してください',
      'please_enter_valid_periods': '有効な回数を入力してください',
      'edit_fixed': '固定費を編集',
      'basic_info': '基本情報',
      'name_label': '名称',
      'fixed_name_hint': '例：住宅ローン、Netflix',
      'monthly_amount': '月額',
      'time_settings': 'スケジュール',
      'start_month': '開始月',
      'set_periods': '期間を設定',
      'total_periods': '総期数',
      'end_month': '終了月',
      'current_progress': '進行状況',
      'progress_fmt': '第{current}回・支払済{done}回・残{remaining}回',
      'notes_optional': 'メモ（任意）',
      'fixed_notes_hint': '例：土地銀行住宅ローン、金利1.78%',
      'backup': 'バックアップ',
      'restore': '復元',
      'export': 'エクスポート',
      'backup_data': 'データをバックアップ',
      'restore_backup': 'バックアップを復元',
      'export_csv': 'CSVでエクスポート',
      'export_excel': 'Excelレポートを出力',
      'backup_export': 'バックアップ＆エクスポート',
      'danger_zone': '危険ゾーン',
      'clear_all_expenses': 'すべての支出を削除',
      'clear_all_confirm_title': '削除を確認',
      'clear_all_confirm_content': 'すべての支出記録が永久に削除されます。元に戻せません。',
      'all_cleared': 'すべての記録を削除しました',
      'no_backup': 'バックアップファイルなし',
      'select_backup': 'バックアップを選択',
      'delete_backup_title': 'バックアップを削除？',
      'delete_backup_confirm': '元に戻せません。このバックアップを削除しますか？',
      'backup_deleted': 'バックアップを削除しました',
      'delete_failed': '削除失敗。後で再試行してください',
      'no_backup_data': 'バックアップがありません',
      'confirm_restore_title': '復元しますか？',
      'confirm_restore_content': '現在のすべてのデータ（支出・固定費・口座・投資）がバックアップで上書きされます。元に戻せません。',
      'restore_label': '復元',
      'select_month': '月を選択',
      'backup_success': '✓ バックアップ完了',
      'restore_success': '✓ 復元完了',
      'export_success': '✓ エクスポート完了',
      'backup_saved': '✓ バックアップ保存：{filename}',
      'backup_failed_msg': 'バックアップ失敗：{error}',
      'csv_exported': '✓ CSVエクスポート：{filename}',
      'excel_exported': '✓ Excelエクスポート：{filename}',
      'export_failed_msg': 'エクスポート失敗：{error}',
      'expense_records': '支出記録',
      'restore_failed_msg': '復元失敗：{error}',
      'fixed_monthly_total': '毎月 NT\$ {amount}',
      'accounts_count': '{n} 口座',
      'holdings_count': '{n} 銘柄',
      'count_unit': '{n} 件',
      'periods_completed': '全 {n} 回完了',
      'periods_remaining_label': '残り {n} 回',
      'welcome_name': 'ようこそ、{name}さん！',
      'delete_confirm_account': '「{name}」を削除しますか？',
      'search_hint': '支出・固定費を検索...',
      'no_results': '結果が見つかりません',
      'search_prompt': '検索ワードを入力してください',
      'date_range': '日付範囲',
      'select_start_date': '開始日を選択',
      'select_end_date': '終了日を選択',
      'select_category': 'カテゴリを選択',
      'done': '完了',
      'help_support': 'ヘルプ＆サポート',
      'rewatch_tour': 'チュートリアルを再視聴',
      'rewatch_tour_subtitle': 'アプリの主な機能を再確認',
      'report_issue': '問題を報告',
      'report_issue_subtitle': 'バグ報告・機能提案・感想',
      'confirm_image': '画像内容を確認',
      'confirm_image_content': 'スクリーンショットに身分証番号・銀行口座・クレジットカード番号・パスワードなどの個人情報が含まれていないことを確認してください。',
      'confirm_submit': '確認して送信',
      'feedback_sent': '送信完了！フィードバックありがとうございます。継続的に改善してまいります。',
      'feedback_failed': '送信失敗しました。後でもう一度お試しいただくか、hello@qoryva.com までご連絡ください。',
      'feedback_intro': '問題・機能提案・使用感想など、お気軽にお知らせください。スクリーンショットがあると調査の参考になります。',
      'feedback_type': 'フィードバック種類',
      'select_feedback_type': 'フィードバック種類を選択',
      'issue_description': '問題の説明',
      'issue_description_hint': '状況・操作手順、または追加してほしい機能を説明してください。',
      'please_fill_issue': '問題を説明してください',
      'please_enter_min_10': '10文字以上入力してください',
      'contact_email': '連絡先メール',
      'contact_email_hint': '返信を希望する場合はメールを残してください',
      'invalid_email': 'メール形式が正しくありません',
      'attach_images': '画像を添付（任意、最大3枚）',
      'submit': '送信',
      'feedback_legal_note': 'フィードバック内容に身分証番号・銀行口座・クレジットカード番号・パスワードなどを含めないでください。提供された内容は問題解決とサービス改善に使用されます。',
      'feedback_cat_usage': '使用上の問題',
      'feedback_cat_feature': '機能提案',
      'feedback_cat_data': 'データ異常',
      'feedback_cat_invest': '投資ページの問題',
      'feedback_cat_backup': 'バックアップ/復元の問題',
      'feedback_cat_other': 'その他',
      'please_enter_name': '名前を入力してください',
      'please_enter_amount': '金額を入力してください',
      'invalid_amount': '無効な金額',
      'confirm_delete': '削除してもよろしいですか？',
      'confirm_clear_all': 'すべてのデータを削除しますか？元に戻せません。',
      'analysis': '支出分析',
      'this_month_short': '今月',
      'two_months': '2ヶ月',
      'half_year': '6ヶ月',
      'invest_overview': 'ポートフォリオ',
      'total_value': '評価額合計',
      'total_cost': '取得原価',
      'total_profit': '損益',
      'holding_detail': '保有銘柄',
      'no_holdings': '保有銘柄なし',
      'add_first_invest': '右上の + をタップして最初の投資を追加',
      'invest_disclaimer': '本機能は個人記録・情報整理用です。投資助言ではありません。投資はご自身の判断で。',
      'shares': '株数',
      'current_price': '現在値',
      'current_value_label': '評価額',
      'est_profit': '推定損益',
      'buy_date': '購入日',
      'buy_reason': '購入理由',
      'sell_strategy': '売却戦略',
      'set_fx_rate': '為替レート設定',
      'no_current_price': '現在値なし',
      'query_price': '現在値を取得',
      'broker': '証券会社',
      'no_accounts_invest_hint': '口座がありません。「管理」で追加してください',
      'fixed_rate_03': '0.3%（固定）',
      'personal_account': 'アカウント',
      'sign_in_gmail': 'Gmailでサインイン',
      'backup_description': 'データのバックアップ・最新機能の通知',
      'google_signin': 'Googleでサインイン',
      'signin_optional': 'ログインは任意です',
      'confirm_logout': 'ログアウトの確認',
      'logout_note': 'ログアウトしてもローカルデータには影響しません。',
      'logout': 'ログアウト',
      'receive_updates': '更新情報を受け取る',
      'receive_updates_subtitle': '新機能の案内を不定期配信、いつでも解除可能',
      'restore_legacy_warning': '⚠ 旧形式のバックアップを復元しました。このバックアップには口座・投資データは含まれません。口座はクリアされました。再作成または手動で残高を修正してください。',
      'restore_success_msg': '✓ 復元完了：支出 {expenses} 件、口座 {accounts} 件、保有銘柄 {holdings} 件',
      'year_label': '{year}年',
      'month_label': '{month}月',
      'onboarding_rewatch_notice': '「ヘルプ＆サポート」からいつでもツアーを再視聴できます',
      'backup_list_item': '支出 {expenses} 件・固定費 {fixed} 件',
      'delete_this_backup': 'バックアップを削除',
      'shares_value': '{n} 株',
      'fee_and_tax_note': '手数料 {fee}%＋税 0.3% 控除後',
      'edit_account': '口座を編集',
      'add_account': '口座を追加',
      'account_settings': '口座設定',
      'custom_name': 'カスタム名',
      'balance': '残高',
      'current_balance': '現在の残高',
      'currency': '通貨',
      'count_in_total': '純資産に含める',
      'edit_entry': '記録を編集',
      'add_income': '収入を追加',
      'type_label': '種別',
      'account_label': '口座',
      'today': '今日',
      'yesterday': '昨日',
      'day_before_yesterday': '一昨日',
      'income_category': '収入カテゴリー',
      'expense_category': '支出カテゴリー',
      'recommended_items': '{category} おすすめ',
      'income_detail': '収入詳細',
      'expense_detail': '支出詳細',
      'note_optional': 'メモ（任意）',
      'update_entry': '記録を更新',
      'save_income': '収入を保存',
      'save_expense': '支出を保存',
      'name_hint': '項目名',
      'edit_holding': '保有株を編集',
      'add_investment': '投資を追加',
      'select_market': '市場を選択',
      'tw_stocks': '🇹🇼  台湾株',
      'us_stocks': '🇺🇸  米国株',
      'code_section_tw': 'コード（例：2330、0050）',
      'code_section_us': 'コード（例：AAPL、TSLA）',
      'code_input_hint_tw': 'コードまたは名称を入力',
      'broker_fee_section_tw': '証券会社と手数料（台湾株）',
      'broker_fee_section_us': '証券会社と手数料（米国株）',
      'fee_label_fmt': '手数料 {fee}',
      'fee_rate': '手数料',
      'tx_tax': '取引税',
      'trade_info': '取引情報',
      'auto_fill': '自動入力',
      'purchase_date': '購入日',
      'linked_account_optional': '口座を紐付ける（任意）',
      'unlinked': '紐付けなし',
      'account_deduct_note': '購入時に総コストが口座から差引かれ、削除時に返金されます。',
      'invest_notes_optional': '投資メモ（任意）',
      'sell_timing': '売却タイミング',
      'buy_reason_hint': '例：AIトレンドに注目',
      'sell_timing_hint': '例：+30%で半分売却',
      'broker_hint_tw': '証券会社名を入力',
      'enter_stock_code': '銘柄コードを入力してください',
      'enter_valid_shares': '有効な株数を入力してください',
      'enter_valid_cost': '有効なコストを入力してください',
      'stock_not_found': '「{code}」が見つかりません。コードを確認してください。',
      'this_bimonth': '隔月',
      'this_half_year': '半年',
      'deleted_item': '「{name}」を削除しました',
      'deleted_holding': '{code}を削除しました',
      'copy_suffix': '（コピー）',
      'price_fetch_failed': '株価を取得できません。接続を確認してください。',
      'price_updated_all': '{n}件の株価を更新しました',
      'price_updated_partial': '{updated}/{total}件の株価を更新しました',
      'streak_record_daily': '毎日記録して連続記録を維持しよう',
      'period_spending_prefix': '{period}の合計支出 ',
      'vs_last_period': '、前期比',
      'spending_increased': '増加',
      'spending_decreased': '減少',
    },
  };

  static String getLocaleKey(Locale locale) =>
      '${locale.languageCode}_${locale.countryCode}';

  static String translate(Locale locale, String key) {
    final k = getLocaleKey(locale);
    final map = _strings[k] ?? _strings['zh_TW']!;
    return map[key] ?? _strings['zh_TW']![key] ?? key;
  }

  static String of(BuildContext context, String key) =>
      translate(Localizations.localeOf(context), key);

  static String ofParam(
      BuildContext context, String key, Map<String, dynamic> params) {
    String str = of(context, key);
    params.forEach((k, v) => str = str.replaceAll('{$k}', v.toString()));
    return str;
  }

  static String translateParam(
      Locale locale, String key, Map<String, dynamic> params) {
    String str = translate(locale, key);
    params.forEach((k, v) => str = str.replaceAll('{$k}', v.toString()));
    return str;
  }

  // Maps zh_TW category name (stored in DB) to current locale
  static final Map<String, String> _categoryKeyMap = {
    '餐飲': 'dining', '饮食': 'dining',
    '教育': 'education',
    '娛樂': 'entertainment', '娱乐': 'entertainment',
    '交通': 'transport',
    '購物': 'shopping', '购物': 'shopping',
    '醫療': 'medical', '医疗': 'medical',
    '住居': 'living',
    '其他': 'other',
    '薪資': 'salary', '薪资': 'salary',
    '獎金': 'bonus', '奖金': 'bonus',
    '投資': 'invest_income', '投资': 'invest_income',
    '退款': 'refund',
    '其他收入': 'other_income',
  };

  static String translateCategory(BuildContext context, String storedName) {
    final key = _categoryKeyMap[storedName];
    if (key == null) return storedName;
    return of(context, key);
  }

  static String formatDateForLocale(DateTime date, Locale locale) {
    try {
      Intl.defaultLocale = '${locale.languageCode}_${locale.countryCode}';
      return DateFormat.yMd().format(date);
    } catch (_) {
      return date.toString();
    }
  }
}

class AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales
      .any((l) => l.languageCode == locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations();

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}
